### ISSUE TITLE
Support for older versions of Rubocop

### ISSUE THREAD

**Issue by benhutchins** [AtomLinter/linter-rubocop#101]
I was starting to get a ton of errors, that my rubocop path was invalid. I kept messing with the `command` and `executablePath` but eventually I found it was that I'm on Rubocop `0.29.1` which does not have a `--cache` argument it was throwing an error that `linter-rubocop` did not handle, and the thrown error didn't provide the response from the [failed command](https://github.com/AtomLinter/linter-rubocop/blob/master/index.coffee#L30) which was a bit of a pain to debug.

However, the fix was just that I had to change the `DEFAULT_ARGS`. It'd be helpful to simply allow these to be replaced from my `~/.atom/config.cson` so it'd allow people to easily set their own arguments (especially since the additional argument support was also dropped).

Another solution might be to first run `rubocop -v` to get the version and dynamically change the `DEFAULT_ARGS` based on the version. I believe this is more work and doesn't add a lot of value long term.

It'd also be helpful to report the response of the failed command as part of the thrown error, so when the command fails it can be more quickly resolved by the user.

If making a new argument that can optionally override the `DEFAULT_ARGS` variable is the right approach I'd be happy to make a PR for that.

**Comment by caseywebdev** [comment]
> especially since the additional argument support was also dropped

This isn't true. You can set your command to `rubocop --other --flags --here` and it will work as expected. As for supporting older versions, STDIN support was only recently added to Rubocop (I believe 0.34.2 is the minimum working version) and it is necessary for this linter.

There is definitely a better way to handle older versions though, potentially via `-v`. A PR to do a minimum version check would be welcome.

**Comment by benhutchins** [comment]
@caseywebdev Interesting. When I set a `-c` argument it caused an arguments parsing problem, I'll need to try that again I guess.

However, after I changed the `DEFAULT_ARGS` locally `linter-rubocop` is working as expected even though I'm using `0.29.1`. Once it started working I moved on though, at some point I'll need to spend time to update my local rubocop version.

Doing a minimum version check however would also be easy to do, but I'd suggest confirming the minimum version.

**Comment by caseywebdev** [comment]
> However, after I changed the DEFAULT_ARGS locally linter-rubocop is working as expected even though I'm using 0.29.1.

It might appear to work, but I believe linting on the fly will always return the same result until the file is saved, which is unexpected.

**Comment by Arcanemagus** [comment]
@der-flo That was filed as https://github.com/AtomLinter/linter-rubocop/issues/257 and fixed in https://github.com/AtomLinter/linter-rubocop/pull/258, please update to v2.2.2 😉.

**Comment by der-flo** [comment]
@Arcanemagus: Oh, thanks!
