### ISSUE TITLE
Error: env: ruby: File name too long

### ISSUE THREAD

**Issue by evanleck** [AtomLinter/linter-rubocop#112]
Hi, I'm getting the following error whenever I open up a Ruby file in Atom:

```
Error: env: ruby: File name too long
    at /Users/evan/.atom/packages/linter-rubocop/index.coffee:30:15
```

I poked around in the source but it wasn't super clear to me what was going on.

Thanks for taking a look!

**Comment by Arcanemagus** [comment]
What is the path to the file you are opening when you see this? Does `rubocop` work on that file from a terminal?

**Comment by evanleck** [comment]
Any Ruby file I open throws this error, for example `/Users/evan/Code/closures.rb` and rubocop works fine from the command line. I'm using rbenv and ran `rbenv which rubocop` to get the right path to the executable.

**Comment by Arcanemagus** [comment]
Hmmm, if you close _all_ Atom instances, and then launch Atom from the terminal (`atom .`) where `rubocop` is working, do you still see this?

**Comment by evanleck** [comment]
Yeah, same same.

**Comment by Arcanemagus** [comment]
Are you on OS X?

**Comment by evanleck** [comment]
Yup!

**Comment by Arcanemagus** [comment]
Okay, first step is to see who is screwing this up: `rbenv` or OS X...

Can you:

- Open Atom's Developer Tools 
- Put a breakpoint [here](https://github.com/AtomLinter/linter-rubocop/blob/v0.4.7/index.coffee#L26)
- Open a Ruby file and trigger a lint
- When you hit the breakpoint run this in the Console:
```js
rbv = helpers.exec('ruby', ['-v'])
```
- Allow the breakpoint to continue, then check the value of `rbv`

Compare the value returned by the Promise with what you see when you run `ruby -v` in the terminal window you launched Atom from.

**Comment by evanleck** [comment]
Alright, running the snippet you gave me raised an error:

```
rbv = helpers.exec('ruby', ['-v'])

Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}

Uncaught (in promise) Error: spawn ENAMETOOLONG(…)exports._errnoException @ util.js:837
ChildProcess.spawn @ internal/child_process.js:298
exports.spawn @ child_process.js:351
module.exports.BufferedProcess.spawn @ /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188
BufferedProcess @ /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52
(anonymous function) @ /Users/evan/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/helpers.js:88
_exec @ /Users/evan/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/helpers.js:62
exec @ /Users/evan/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/helpers.js:136
(anonymous function) @ VM727:1
InjectedScript._evaluateOn @ VM682:904
InjectedScript._evaluateAndWrap @ VM682:837
InjectedScript.evaluateOnCallFrame @ VM682:963
lint @ index.coffee:26
linters.forEach.promises.push.Promise.then._this.emitter.emit.linter @ linter-registry.js:63
(anonymous function) @ linter-registry.js:62
lint @ linter-registry.js:60
(anonymous function) @ linter.coffee:98
module.exports.Emitter.simpleDispatch @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25
module.exports.Emitter.emit @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125
(anonymous function) @ editor-linter.js:80
(anonymous function) @ helpers.coffee:23
```

And `rbv` after continuing script execution gives me this:

```

Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn …}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/evan/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/helpers.js:88:81
    at _exec (/Users/evan/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/helpers.js:62:10)
    at Object.exec (/Users/evan/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/helpers.js:136:10)
    at Object.eval (eval at evaluate (unknown source), <anonymous>:1:15)
    at Object.InjectedScript._evaluateOn (<anonymous>:904:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:963:21)
    at Object.lint (/Users/evan/.atom/packages/linter-rubocop/index.coffee:26:3)
    at linters.forEach.promises.push.Promise.then._this.emitter.emit.linter (/Users/evan/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/evan/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/evan/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/evan/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/evan/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/evan/.atom/packages/linter/lib/helpers.coffee:23:18code: "ENAMETOOLONG"errno: "ENAMETOOLONG"message: "spawn ENAMETOOLONG"rawStack: Array[22]stack: (...)get stack: ()set stack: ()syscall: "spawn"__proto__: DefineError.aV
```

**Comment by Arcanemagus** [comment]
@steelbrain Is this possibly something to do with the environment fixing? Looks like no matter what is ran it runs into that.

**Comment by steelbrain** [comment]
I'm familiar with the `ENAMETOOLONG` error on windows. It happens when there's deep nesting of npm packages and the path to open/execute gets too long for the OS. If it was an env issue, there would be a timeout or similar warning in the console and everything else would work as usual.

It would be very helpful if the user would tell you their `rubocop` path

**Comment by evanleck** [comment]
Running `which rubocop` yields `/Users/evan/.rbenv/shims/rubocop` and running `rbenv which rubocop` yields `/Users/evan/.rbenv/versions/2.3.0/bin/rubocop`. I have the latter in my settings for `linter-rubocop`

**Comment by Arcanemagus** [comment]
Is there anyway to test this _without_ `rbenv`? Most people seem to be using `rvm` to manage their Ruby versions, and although it has it's own issues (you need to create wrapper scripts for running tools in anything other than a terminal... like from within Atom), I've never seen this issue reported from somebody using it.

**Comment by evanleck** [comment]
So I uninstalled `rbenv` and the problem seems to have gone away. That said, switching to `rvm` hardly seems like a solution. Do you have any ideas where that excessively long path name could be coming from?

**Comment by Arcanemagus** [comment]
I would imagine it comes from some hack to the environment that `rbenv` is doing, I personally don't use either of them as I'm not a Ruby developer so I'm not positive where it is breaking things.

**Comment by Arcanemagus** [comment]
You could try filing a report on the `rbenv` repo as they might know where to track down the issue?

Marking this as closed as this isn't a problem with `linter-rubocop`, but feel free to continue the discussion.

**Comment by evanleck** [comment]
I get that this may not be a `linter-rubocop` issue at its heart, but what makes you think it's something that `rbenv` is doing? `rbenv` is referenced in the settings for `linter-rubocop` so I doubt I'm the only person using `rbenv` _and_ this plugin.

**Comment by Arcanemagus** [comment]
What makes me think this is something `rbenv` is doing is this:
"So I uninstalled `rbenv` and the problem seems to have gone away."

I don't know anything about what `rbenv` is doing to manage Ruby versions, it's quite possible that it does something similar to `rvm` where it modifies how the shell is calling the programs (a possible source of the error you are seeing).

Troubleshooting how it is breaking things is beyond the scope of this project though. @caseywebdev have you seen anything like this before or have any experience with it?

**Comment by evanleck** [comment]
Fair enough, for sure.

I'm not super familiar with how it works either but I believe it operates somewhat differently than `rvm`.

I'll try and dig through some stuff and figure out where the error is originating.

**Comment by evanleck** [comment]
Looks like this _could_ be related to an issue with my `$PATH` variable as it is getting read into Atom. After I hit the error and run `process.env` in the console, I see `process.env.PATH` as this:

```
"begin; function be --wraps bundle; bundle exec $argv; end ;end <&3 3<&- begin; function bem --wraps bundle; bundle exec middleman $argv; end ;end <&3 3<&- begin; function brewup --wraps brew; brew update; brew upgrade --all; brew cleanup; brew prune $argv; end ;end <&3 3<&- begin; function flushdns --wraps sudo; sudo discoveryutil mdnsflushcache; sudo discoveryutil udnsflushcaches $argv; end ;end <&3 3<&- begin; function g --wraps git; git $argv; end ;end <&3 3<&- /Users/evan/.rbenv/shims /opt/X11/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin"
```

Which looks pretty wacky. I'm still trying to figure out where some of that is coming from, but I suspect either [`omf`](https://github.com/oh-my-fish/oh-my-fish) or something in my shell setup is causing the issue.

Sorry for misattributing this issue to the plugin! I will update this thread with more info as I get to it.

**Comment by evanleck** [comment]
Do y'all know where Atom gets its SHELL variable from? It still says it's using `fish` even after I've run `chsh -s /usr/local/bin/zsh` and `zsh` pulls up for new terminal windows.

**Comment by Arcanemagus** [comment]
Depends on a lot of different things, I think one of the biggest factors is only in v1.7.0-beta0 and above (Atom's built in attempt to fix OS X giving it a blank environment). The helper library used to execute programs also does several things to attempt to work around this issue, @steelbrain would be the one to talk to for that.

It looks to me like something is sticking several parts of an init script in there, possibly a missing `'` or `"` somewhere in your login script?

**Comment by evanleck** [comment]
Could be, I use `oh-my-fish` and my `~/.config/omf/init.fish` script looks like this:

```
alias be 'bundle exec'
alias bem 'bundle exec middleman'
alias brewup 'brew update; brew upgrade --all; brew cleanup; brew prune'
alias flushdns 'sudo discoveryutil mdnsflushcache; sudo discoveryutil udnsflushcaches'
alias g git

function trash
  mv $argv ~/.Trash/
end

# Load autojump
[ -f /usr/local/share/autojump/autojump.fish ]; and . /usr/local/share/autojump/autojump.fish

# Load rbenv
# status --is-interactive; and . (rbenv init -|psub)
```

**Comment by steelbrain** [comment]
@evanleck Please note that you have to restart your user after switching your shell. Also I recommend [`Rick's Guide`](http://rick.cogley.info/post/use-homebrew-zsh-instead-of-the-osx-default/) for switching/upgrading shells

**Comment by evanleck** [comment]
@steelbrain ah you have to log out of your user session for it take effect? I didn't realize that so that's probably part of that issue. And yeah, I use the `brew` version of `zsh` and `fish`
