### ISSUE TITLE
Search for common rubocop config locations

### ISSUE THREAD

**Issue by getaaron** [AtomLinter/linter-rubocop#113]
If I have a directory open in Atom, I would like linter-rubocop to search for these config files, and load them if found:

```
./arcanist/lint/rubocop.yml
./.rubocop.yml
```

**Comment by caseywebdev** [comment]
Rubocop searches up the directory tree starting at the file you're trying to lint. You can manually specify a different config file location in the `command` option if you'd like.

**Comment by getaaron** [comment]
OK, I guess that'll do for now. Thanks. Something like https://github.com/AtomLinter/linter-rubocop/issues/87 would be nice too.
