### ISSUE TITLE
Not using correct ruby version since Atom 1.7

### ISSUE THREAD

**Issue by mneumark** [AtomLinter/linter-rubocop#117]
I used to have some coffeescript in my init script that would set variables for my `PATH` and `GEM_HOME` and such for `chruby` to get the correct version of rubocop running. That would allow this linter to choose the correct versions of things.

That stopped working in Atom 1.7 due to the addition of the environment being inherited from the terminal (it seems to run my bash_profile and such correctly and get the right `PATH`). But now, even though my environment seems correct, and even though I set my rubocop command to: 
`/Users/$USER/.gem/ruby/2.2.3/bin/rubocop`
and even though the top line of this file is:
`#!/Users/$USER/.rubies/ruby-2.2.3/bin/ruby`

It does not seem to find the correct version. Therefore, it alerts me to syntax errors because I have a method with keyword args with no default value, which is perfectly fine in any modern version of Ruby. So clearly its using an old version.

Any idea why it would do this? Maybe this is a Linter issue and not specific to rubocop? Or maybe it is linter-rubocop's fault. Any thoughts?

**Comment by mneumark** [comment]
Nevermind. I discovered the TargetRubyVersion option. Solved the problem!

**Comment by robzolkos** [comment]
@mneumark can you please explain how you fixed this? (I think I've got the same problem)

**Comment by mneumark** [comment]
I added a section to my .rubocop.yml file:
```yml
AllCops:
  TargetRubyVersion: 1.9
```

**Comment by robzolkos** [comment]
@mneumark thank you 👍
