### ISSUE TITLE
Feature request: disable rubocop linter if no config file is present

### ISSUE THREAD

**Issue by mdub** [AtomLinter/linter-rubocop#118]
I would like to enable the rubocop listing if-and-only-if a `.rubocop.yml` file is present (in the project directory, or a parent directory).

Currently, the linter will run (with default settings) even if no config file is present.  Is it possible to disable it?

**Comment by Arcanemagus** [comment]
It's not currently possible, marking this as a feature request. If anyone wants to put together a PR implementing this I'd be happy to review it :wink:.

**Comment by JackChance** [comment]
I'm not sure this is desirable even. Without a .rubocop.yml present it lints with its default .rubocop.yml, and I can't be the only one that has decided that the default works for me.

**Comment by Arcanemagus** [comment]
@JackChance This should be behind an option, just like every other linter plugin that has a similar feature.

**Comment by JackChance** [comment]
Apologies, I misunderstood the ask. I thought @mdub wanted to make this default instead of an option.

**Comment by Arcanemagus** [comment]
That's how it reads, but putting this behind a toggle is the only way it should be merged, specifically for the reason you posted :wink:.

**Comment by mdub** [comment]
Yes, I imagined it would be a toggle, and default to the current behaviour.
