### ISSUE TITLE
Feature Request: Allow custom severity level mappings

### ISSUE THREAD

**Issue by davefp** [AtomLinter/linter-rubocop#124]
## Problem

Atom-linter supports 3 severity levels:
- info
- warning
- error

While rubocop has 5:
- refactor
- convention
- warning
- error
- fatal

In my environment, warning and above will break the build while refactor and convention will not. It would be useful if I could display refactor and convention offences as info level to reflect this.
## Suggestion:

Have a hash setting that allows rubocop severities to be mapped onto atom-linter severities like so:

```
'linter-rubocop':
  'severity-mapping':
    'info': ['refactor', 'convention']
    'warning': ['warning']
    'error': ['error', 'fatal']
```

(Or whatever valid CSON should look like)

If I worked on a PR for this would it be considered for merging?

**Comment by Arcanemagus** [comment]
@caseywebdev is the maintainer here, but I'd certainly consider it if you can think of a good UI for implementing it.

Just a note that the currently released version of `linter` only respects the `type` attribute, defining some styles for some guessed values, the `severity` attribute is new and uses a predefined list... but won't be supported until a version of `linter` is released that utilizes `linter-ui-default`.

**Comment by caseywebdev** [comment]
Sounds reasonable to me. I'm wondering if those should just be the defaults?

**Comment by maschwenk** [comment]
I'm not sure what the status of things was at the time of this feature request. But this is now implemented as such: https://github.com/AtomLinter/linter-rubocop/blob/master/src/index.js#L103-L109
