### ISSUE TITLE
Could not find proper version of rubocop (0.37.0) in any of the sources

### ISSUE THREAD

**Issue by perlun** [AtomLinter/linter-rubocop#125]
I get this error when opening one of my projects. It works fine with others. Unfortunately, I have a situation where I'm using different versions of Rubocop for different projects:

```
Error: [31mCould not find proper version of rubocop (0.37.0) in any of the sources[0m
[33mRun `bundle install` to install missing gems.[0m
    at /Users/plundberg/.atom/packages/linter-rubocop/index.coffee:30:15
```

I tried overriding the `executablePath` like this, to no avail (in `config.cson`):

```
'linter-rubocop':
  'executablePath': '/usr/local/bin/rubocop'
```

Running version 0.4.7. Any suggestions? I have rubocop 0.37 installed in my system-wide Ruby, but I wonder if my `rvm` or `.ruby-version` messes things up in this case...

**Comment by perlun** [comment]
Weird. _This works_ if I start Atom from the dock, but not if I run it like `atom .` (which I have to do in some projects). Extremely weird and unpredictable! Closing anyhow.

**Comment by cd-rum** [comment]
+1, but running from the dock doesn't help me. I've got this issue too, and I use rvm too. Any help?

**Comment by Arcanemagus** [comment]
Have you seen the hints in the readme in the ["Using RVM"](https://github.com/AtomLinter/linter-rubocop#using-rvm) section?

**Comment by cd-rum** [comment]
Running Atom from the Terminal like `atom .` (the opposite to @perlun's fix) it works. Even weirder.

**Comment by Arcanemagus** [comment]
Sounds like yours is just the standard "OS X completely fails at providing applications with a proper environment" issue.

**Comment by perlun** [comment]
I have seen that sometimes `atom .` is the way to make it work here as well, lately.

**Comment by Arcanemagus** [comment]
@perlun That's the simplest, and best, way to get your environment correct, as Atom will inherit the environment it is _first_ launched from (and some of the environment from subsequent launches now). So opening Atom initially from a terminal where things are already setup is the best way to ensure it is working properly.

**Comment by chen199** [comment]
@perlun 
I know it sounds a bit strange, but i just removed the 'linter-rubocop' section of the cson file, installed the rubocop gem, and it just works without the annoying error message.
I'm not running this on OSX, but rather ubuntu 14.04.

**Comment by jeremykirc** [comment]
> Have you seen the hints in the readme in the ["Using RVM"](https://github.com/AtomLinter/linter-rubocop#using-rvm) section?

Per the linked doc, changing `bin` to `wrappers` worked for me
