### ISSUE TITLE
linter-rubocop messes up Atom's PATH on Windows, interfering with other packages

### ISSUE THREAD

**Issue by Ajedi32** [AtomLinter/linter-rubocop#128]
In Windows, environment variable names are case insensitive. My installation of Windows (Windows 7) uses CamelCase for the `PATH` environment variable (e.g. `Path`), which seems to be causing this plugin to overwrite the PATH in Atom with "undefined".

Before using `linter-rubocop`:

``` javascript
Object.keys(process.env).filter((x) => x.toLowerCase() === 'path')
//=> ["Path"]
```

After using `linter-rubocop`:

``` javascript
Object.keys(process.env).filter((x) => x.toLowerCase() === 'path')
//=> ["Path", "PATH"]
process.env.PATH
//=> undefined
```

This behavior causes several other Atom Packages to malfunction. For example, [`atom-terminal`](https://atom.io/packages/atom-terminal) no longer works, and [`platformio-ide-terminal`](https://atom.io/packages/platformio-ide-terminal) has a messed up path in the shell.

This behavior does not occur when `linter-rubocop` is disabled, nor does it occur when using other [`linter`](https://github.com/steelbrain/linter) plugins such as [`linter-jshint`](https://atom.io/packages/linter-jshint).

**Comment by Ajedi32** [comment]
So after inspecting the source code of this package and not finding any immediately obvious code which assigns to Path, I ran `Object.defineProperty(process.env, 'PATH', {enumerable: false, configurable: false, writable: false})` in order to expose the offending code, and got the following stack trace:

```
TypeError: Cannot assign to read only property 'PATH' of #<Object>
    at assign (native)
    at _exec (C:\Users\ajedi32\.atom\packages\linter-rubocop\node_modules\atom-linter\lib\helpers.js:60:3)
    at Object.exec (C:\Users\ajedi32\.atom\packages\linter-rubocop\node_modules\atom-linter\lib\helpers.js:136:10)
    at Object.lint (file:///C:/Users/ajedi32/.atom/packages/linter-rubocop/index.coffee:27:11)
    at promises.push.Promise.then._this.emitter.emit.linter (C:/Users/ajedi32/.atom/packages/linter/lib/linter-registry.js:63:26)
    at C:/Users/ajedi32/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (C:/Users/ajedi32/.atom/packages/linter/lib/linter-registry.js:60:18)
    at file:///C:/Users/ajedi32/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ajedi32\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\ajedi32\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:/Users/ajedi32/.atom/packages/linter/lib/editor-linter.js:80:22
    at file:///C:/Users/ajedi32/.atom/packages/linter/lib/helpers.coffee:23:18
```

The offending line: [atom-linter\lib\helpers.js:60](https://github.com/steelbrain/atom-linter/blob/v4.3.0/lib/helpers.js#L60)

**Comment by Ajedi32** [comment]
The latest version of that package is totally different from the version being used here. It's possible that upgrading 5+ might fix this problem.

**Comment by Ajedi32** [comment]
Related: #126

**Comment by Arcanemagus** [comment]
The 5.x branch actually has several issues with Windows that haven't been resolved yet, when those are fixed the plugins can be upgraded.

**Comment by Ajedi32** [comment]
Sounds good. In the meantime, I was able to work around this by going to Control Panel -> Edit the system environment variables, updating the casing of the PATH variable (from `Path` to `PATH`) in both the System and User variable sections, then rebooting.

**Comment by Arcanemagus** [comment]
Btw, Windows systems are _awesome_ in that some will have _both_ `Path` and `PATH`, requiring you to check both. Isn't that "useful"? 😛😭

**Comment by Arcanemagus** [comment]
Closing this, it was a bug in a dependency that has since been fixed.
