### ISSUE TITLE
RuboCop is not installed

### ISSUE THREAD

**Issue by firedev** [AtomLinter/linter-rubocop#14]
I see `RuboCop is not installed` in status bar now all of a sudden, it is installed, and I put the path to executable in settings. It was working fine but then it stopped working. I am not sure if this is a caused by `atom-lint` or `linter-rubocop` itself. Please advise.

**Comment by DarthSim** [comment]
@hd-deman Sorry to disturb, no problem with this plugin, there's only stupid me. I installed Atom Lint instead of Linter :)
