### ISSUE TITLE
Any way to support .ruby-version?

### ISSUE THREAD

**Issue by tonytonyjan** [AtomLinter/linter-rubocop#144]
If `.ruby-version` exists and it contains an MRI version, it is used by rubocop by default. But linter-rubocop seems to ignore it. Is it possible to make it work?

**Comment by tonytonyjan** [comment]
FYI: https://github.com/AtomLinter/linter-rubocop/blob/34ad5e58281fd62ca14bb99ba0c1c2e155a54704/lib/index.coffee#L24

**Comment by Arcanemagus** [comment]
Is the line you highlighted getting the wrong current working directory? (It's admittedly a bizarre way of getting that...)

**Comment by tonytonyjan** [comment]
I found that rubocop will not make use of `.ruby-version` in subdirectories, in other words, all source code should locate in project root directory, however, `.rubocop.yml` seems work in subdirectories. I am not sure if this issue belongs to linter-rubocop or rubocop.

**Comment by Arcanemagus** [comment]
If `rubocop` itself isn't working, then this certainly won't as it is just a translator of the output of `rubocop` into a format Linter understands. You should definitely file an issue on their bug tracker about that 😉.
