### ISSUE TITLE
Switch parsing to json format, and display cop name in violations

### ISSUE THREAD

**Issue by paradox460** [AtomLinter/linter-rubocop#15]
Currently, this plugin uses the emacs formatting mode. If it were to switch to the json parsing mode, you gain a few things that you couldn't do otherwise:

+ **Display the cop name in the error message (Eg: LineLength):** This is useful if you need to figure out the name of the cop thats giving you grief, and add it to the ignore file or inline ignore comments
+ **Take advantage of JSON:** This plugin is written in CoffeeScript. CoffeeScript is javascript. Javascript can parse JSON very easily.
+ **Future-proof:** While its unlikely the emacs format will change, Rubocop may gain new features that cannot be taken advantage of by the plugin, as they do not show up in the emacs format, but are likely to appear in the JSON format

The biggest attraction for me is the display of cop names

**Comment by caseywebdev** [comment]
We're doing both of these now.
