### ISSUE TITLE
Stopped working since Yosemite

### ISSUE THREAD

**Issue by spape** [AtomLinter/linter-rubocop#16]
All my other linters still work but linter-rubocop stopped working since Yosemite upgrade.
## Without path set

![bildschirmfoto 2014-10-19 um 14 38 53](https://cloud.githubusercontent.com/assets/851393/4693142/3e78007e-578d-11e4-9370-ab0a0ba7d70b.png)

I get an error message:

![bildschirmfoto 2014-10-19 um 14 39 26](https://cloud.githubusercontent.com/assets/851393/4693140/2c5b7dda-578d-11e4-9400-47e774ae1e8f.png)
## With path

I get no error but also no linter results (it just shows nothing).

![bildschirmfoto 2014-10-19 um 14 35 30](https://cloud.githubusercontent.com/assets/851393/4693132/bcc6e91e-578c-11e4-94f2-16205f38e8ba.png)

![bildschirmfoto 2014-10-19 um 14 40 08](https://cloud.githubusercontent.com/assets/851393/4693146/6f70b842-578d-11e4-8b69-ca035e4c342a.png)

![bildschirmfoto 2014-10-19 um 14 44 34](https://cloud.githubusercontent.com/assets/851393/4693156/c1cddb42-578d-11e4-92d6-18164ec1c697.png)

**Comment by sekel** [comment]
+1 same issue

**Comment by maksimf** [comment]
Still the same issue, works only with @BlakeTurner's workaround

**Comment by Eschon** [comment]
Same issue here but @BlakeTurner's workaround didn't work for me on OS X 10.10.3

**Comment by mitnal** [comment]
I don't use this workaround anymore because its working fine for me on OS X 10.10.3 with rubocop 0.30.1. 

But I had the problem that linter-rubocop stopped working with no error message. I found out that I had an old not supported entry in my .rubocop.yml file. 
Perhaps its worth a shot to see if rubocop is running without warnings and errors.

**Comment by Eschon** [comment]
I read through https://github.com/atom/electron/issues/550 and found out that it works for me when I start it thorough the console. All other workarounds don't work for me.

**Comment by BlakeTurner** [comment]
Yeah my workaround stopped working for me when I moved to 10.10.1.

**Comment by ypresto** [comment]
my problem was below...

```
$ rubocop
rbenv: rubocop: command not found

The `rubocop' command exists in these Ruby versions:
  2.1.1
```
It would be better to notify if exited unexpectedly.

**Comment by ryanmt** [comment]
For me, my path was set fine, but my shell login settings for GEM/RUBY settings weren't okay.  I was short on time, so I set my GEM_HOME, RUBY_ROOT, and GEM_PATH explicitly in my init.coffee file.

**Comment by maschwenk** [comment]
Closing due to staleness, please bump if still an issue
