### ISSUE TITLE
Error: /usr/bin/env: ruby_executable_hooks: No such file or directory

### ISSUE THREAD

**Issue by abhayn-webonise** [AtomLinter/linter-rubocop#165]
Error: /usr/bin/env: ruby_executable_hooks: No such file or directory
    at /home/webonise/.atom/packages/linter-rubocop/index.coffee:30:15

**Comment by tobob** [comment]
+1

**Comment by Arcanemagus** [comment]
Are you using some sort of Ruby version management system? (eg. RVM?) What OS are you using?

**Comment by abhayn-webonise** [comment]
@Arcanemagus : Yep. I am using RVM. I am working on ubuntu 14.04

**Comment by tobob** [comment]
![screenshot from 2016-09-29 11-37-10](https://cloud.githubusercontent.com/assets/3189332/18948888/3494254c-8639-11e6-8a1d-d57c98a78483.png)

Ok, for me works like that

**Comment by Arcanemagus** [comment]
@abhayn-webonise If you are using RVM you need to use the wrapper script as @tobob discovered. RVM works it's "magic" using shell macros that don't work in external programs, thus you need the wrapper script.
