### ISSUE TITLE
Feature idea: CMD+click on the linter issue starts rubocops with auto-correct option

### ISSUE THREAD

**Issue by haberbyte** [AtomLinter/linter-rubocop#17]
I would like to see the following feature:

Since rubocop can auto-correct some linter offenses, it would be great if CMD-clicking on an issue would trigger rubocop with the options:

`-a --only $COP ...`

This would allow selectively auto-correcting some linter warnings in case the cop supports auto-correct.

What would be necessary to achieve this? To get the cop-names there is the `-D` flag, so i guess all the information is there.
I would be willing to help.

**Comment by rposborne** [comment]
:+1:

**Comment by gagor** [comment]
:+1:

**Comment by steelbrain** [comment]
I think the hyperclick package's service would come in handy here.

**Comment by shir** [comment]
Looks like linter starting with version 2 have some API for it. Any plans to support it?

**Comment by steelbrain** [comment]
For anyone wanting to implement it, Linter v2 API supports [`solutions`](http://steelbrain.me/linter/types/linter-message-v2.html)

**Comment by maschwenk** [comment]
There's certain autocorrects that would need to run on the entire file, and I'm just a little unsure how I'd be able to differentiate those

**Comment by Arcanemagus** [comment]
You can add a command to trigger a fix [like this](https://github.com/AtomLinter/linter-eslint/blob/6b52abbaa5e37808bc5594e953a953f61fc33be5/src/main.js#L128-L132), and even add an option to the right click menu [like this](https://github.com/AtomLinter/linter-eslint/blob/6b52abbaa5e37808bc5594e953a953f61fc33be5/src/main.js#L159-L179)

Where that calls `this.fixJob()` you would want to call RuboCop with the `--auto-correct` option.
