### ISSUE TITLE
How to debug failing Rubocop?

### ISSUE THREAD

**Issue by RichardJECooke** [AtomLinter/linter-rubocop#173]
Hi, I've followed the readme but I see no effect on my screen. Rubocop neither fails nor succeeds - it shows nothing.

What steps can I follow to see what it's doing, or view a log, or error messages?  There's nothing in the readme on how to debug it.

Thanks.

**Comment by Arcanemagus** [comment]
It looks like this package hasn't yet been updated to automatically install [Linter](https://atom.io/packages/Linter) for you, can you make sure you have that installed and see if it starts working? This package is merely a service provider that you need a consumer for for it to work.

**Comment by maschwenk** [comment]
Should be closed by https://github.com/AtomLinter/linter-rubocop/pull/191
