### ISSUE TITLE
Default Exclude for Metrics/BlockLength do not seem to be respected

### ISSUE THREAD

**Issue by stefansedich** [AtomLinter/linter-rubocop#174]
The defaults for this rule exclude specs, running from the command line I get no warnings, but I do within Atom.

If I were to manually add the exclude to my projects .rubocop.yml it works as expected, is there anything else I need to configure?

**Comment by aaronmallen** [comment]
👍

**Comment by Arcanemagus** [comment]
If you run the following on the CLI, do you see this issue?

```
cat foo.rb | rubocop --cache false --force-exclusion --display-style-guide --stdin foo.rb
```

Essentially all this package does is run the above (with `--format json` included) and parse the results...

**Comment by stefansedich** [comment]
Looks like this is related to what context it is ran in, I have not gone digging but if the file is a spec for example:

`cat foo_spec.rb | rubocop --cache false --force-exclusion --display-style-guide --stdin foo_spec.rb`

Then the default rules for ignoring the specs are not applied, but if I were to do something like this:

`cat spec/foo_spec.rb | rubocop --cache false --force-exclusion --display-style-guide --stdin spec/foo_spec.rb`

The rules apply and everyone is happy.

**Comment by Arcanemagus** [comment]
Ah, and `rubocop` is being run from the directory of the file, not the project root. If there are rules that are sensitive to this we can update where it is ran from.

**Comment by stefansedich** [comment]
I think if it is just run from the root with the full relative path for the files it should be enough to keep everything happy?

**Comment by maschwenk** [comment]
@stefansedich we now run from the project root. Let me know if this problem still persists?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
