### ISSUE TITLE
high cpu usage on save

### ISSUE THREAD

**Issue by jondot** [AtomLinter/linter-rubocop#178]
Hi all,
When I run rubocop through the terminal I barely get a blimp of a cpu usage:

![image](https://cloud.githubusercontent.com/assets/83390/20701077/acc74ff2-b619-11e6-8dba-297bacece9c6.png)

When I save a file I get this huge spike:

![image](https://cloud.githubusercontent.com/assets/83390/20701096/be29d6de-b619-11e6-9867-fac9a27d5176.png)

I suspect perhaps rubocop is being run many times at once?

WDYT?

**Comment by jondot** [comment]
Actually found out the reason. I'll leave this here for reference.

**Comment by Arcanemagus** [comment]
Closing based on the linked issue, although just a note: This should only ever be making _one_ call to that per lint call (and that should be cached!) so you might file another issue on [steelbrain/exec](https://github.com/steelbrain/exec) as to why that is being called more than once in the first place.

Thanks for filing this issue!
