### ISSUE TITLE
v0.5.1 Does not work in Atom Beta

### ISSUE THREAD

**Issue by mattaschmann** [AtomLinter/linter-rubocop#179]
I'm using Atom v1.13-beta6.  The upgrade to 0.5.1 seems to have broken lint messages for rubocop.  I switched back to Atom v1.12.x and it works.  I've downgraded the plugin to 0.5.0 and confirmed it works in Atom 1.13.

**Comment by Arcanemagus** [comment]
Are you getting any error messages? Or are results just not showing up?

What OS are you on? (The [beta build](https://travis-ci.org/AtomLinter/linter-rubocop/jobs/179844662) on Ubuntu Precise worked just fine.)

**Comment by mattaschmann** [comment]
No error messages in the console, I just have no errors on the file (i.e. 'File #') in bottom left is 0 and no lines are marked in my file.  I'm on OSX 10.11.6.  I can try stepping through the code later when I have more time.

**Comment by mattaschmann** [comment]
I should mention that I use the default configs for the plugin, but I've checked the 'which rubocop' and used that executable to run the command in the console and verified that rubocop is working as expected.  Also, as I mentioned before, 0.5.0 works just fine for me.

**Comment by Arcanemagus** [comment]
Ah, what language package are you using for Ruby?

**Comment by mattaschmann** [comment]
language-ruby v0.70.2.  I also have language-ruby-on-rails v0.25.1 if that makes a difference.

**Comment by Arcanemagus** [comment]
It makes a difference if that's the language provider actually being used for the file 😉. I'll push out an update within the hour adding that language to the list that will activate this package.

**Comment by Arcanemagus** [comment]
Also added `language-chef` as that's one of the scopes we support.

**Comment by Arcanemagus** [comment]
v0.5.2 should fix this for you, if it doesn't let me know!

**Comment by mattaschmann** [comment]
It does indeed, thanks so much @Arcanemagus!
