### ISSUE TITLE
this happens whenever I close a tab

### ISSUE THREAD

**Issue by wjordan213** [AtomLinter/linter-rubocop#18]
I am using Mac OSX mavericks version 10.9.5. This unfortunately makes rubocop a huge hassel to use! I wish that I could help but I am still just learning the basics of programming.
The console pops up taking up a significant portion of the screen and i get this error below. I had trouble uploading the screen shot I took so i just had to copy paste sorry.

activate linter-rubocop /Users/wjordan213/.atom/packages/linter-rubocop/lib/init.coffee:7
Window load time: 1714ms index.js:46
3Uncaught Error: This TextEditor has been destroyed /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:989
Uncaught Error: This TextEditor has been destroyed /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:989module.exports.DisplayBuffer.screenPositionForBufferPosition /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:989module.exports.Marker.getHeadScreenPosition /Applications/Atom.app/Contents/Resources/app/src/marker.js:211Marker /Applications/Atom.app/Contents/Resources/app/src/marker.js:45module.exports.DisplayBuffer.getMarker /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1188module.exports.DisplayBuffer.markBufferRange /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1220module.exports.TextEditor.markBufferRange /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1216LinterView.display linter-view.coffee:180LinterView.processMessage linter-view.coffee:159(anonymous function) linter-view.coffee:1(anonymous function) linter-view.coffee:142Linter.processMessage linter.coffee:151(anonymous function) linter.coffee:127BufferedProcess.triggerExitCallback /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:52(anonymous function) /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:59(anonymous function) /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:105emit events.js:129(anonymous function) net.js:461

**Comment by Arcanemagus** [comment]
Closing this, this was either an Atom internal bug, or related to some ancient version of this package that has no relation to how it works currently.
