### ISSUE TITLE
Automatic linting broken (v0.5.1)

### ISSUE THREAD

**Issue by Tybot204** [AtomLinter/linter-rubocop#180]
I updated linter-rubocop today to v0.5.1, and it no longer is linting my files! The status of every file says "No Issues" always, even when basic syntax errors are present. Running Rubocop manually in a terminal finds the errors correctly, leading me to believe it is this plugin and not Rubocop. Other linter plugins seem to work fine as well.

EDIT: I am running Atom 1.10.2 on Ubuntu 16

**Comment by Tybot204** [comment]
This seems related to https://github.com/AtomLinter/linter-rubocop/issues/179, although I am not running a beta version of Atom.

**Comment by Arcanemagus** [comment]
@Tybot204 what language provider are you using for Ruby files?

**Comment by Tybot204** [comment]
@Arcanemagus I was using Auto Detect, which determined the language to be Ruby on Rails. I messed around with which language I was using and found some interesting results:
Ruby works fine in all cases. Ruby on Rails (RJS) does not work in any case that I tried. Ruby on Rails does not work by default, but when I switch to Ruby (which works) and then back to Ruby on Rails, it begins linting correctly.

**Comment by Tybot204** [comment]
Package versions:
language-ruby -- 0.70.2
language-ruby-on-rails -- 0.25.1

**Comment by Tybot204** [comment]
Just read the update to https://github.com/AtomLinter/linter-rubocop/issues/179 and that will probably solve this issue as well.

**Comment by Arcanemagus** [comment]
Marking this as a duplicate then, thanks for responding!
