### ISSUE TITLE
v0.5.2 not automatically linting Chef code

### ISSUE THREAD

**Issue by andrewrawson** [AtomLinter/linter-rubocop#185]
Automatic linting of Chef code stopped working in v0.5.1, looks like due to the change to only activate on language-ruby in that release.  In v0.5.2, language-ruby-on-rails and language-chef were added to the activationHooks, but with an apparent typo in language-chef ("chec" vs. "chef"). PR #184 opened with fix.

Thanks for your work on this linter!

**Comment by Arcanemagus** [comment]
Fixed in #184.
