### ISSUE TITLE
Package Dependency on AtomLint

### ISSUE THREAD

**Issue by maschwenk** [AtomLinter/linter-rubocop#189]
@Arcanemagus I see you're a maintainer for this package

https://www.npmjs.com/package/atom-package-deps

My friend tried to install the new Rubocop last night and it took forever for me to realize that he didn't have Atom Linter installed. Would it make sense to utilize this package for making sure that's installed first?

**Comment by maschwenk** [comment]
In progress https://github.com/AtomLinter/linter-rubocop/pull/191

**Comment by Arcanemagus** [comment]
Absolutely, almost all the other providers already do 😉.

**Comment by maschwenk** [comment]
Closed by #191
