### ISSUE TITLE
Style/FileName fails in Atom, succeeds on command line

### ISSUE THREAD

**Issue by TimMoore** [AtomLinter/linter-rubocop#19]
This is an edge-case that happens when you configure Rubocop to check `Gemfile`. It passes on the command line, but fails in Atom with "Use snake_case for source file names."

The check in Rubocop is written so that any filenames that are explicitly _included_ in the configuration are considered "good" and ignored:

https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/file_name.rb#L14

```ruby
return if config.file_to_include?(file_path)
```

This fails when run within Atom because it uses a temporary file, which doesn't match the glob `**/Gemfile`.

```
stdout /var/folders/18/3c9l9tvs5qv9kjg_1nkxtp6m0000gn/T/AtomLinter114111-58971-gmptoasource.ruby.rails/Gemfile:1:1: C: Use snake_case for source file names.
```

Paths are computed relative to the Rubocop config file, so maybe one solution to this could be to copy the config file to the tmp directory, too, and run it from there. If that sounds like an OK solution to the maintainers, I can work up a patch.

**Comment by sekel** [comment]
@TimMoore +1 for your solution.

**Comment by hd-deman** [comment]
@TimMoore sounds good for me. waiting for your PR

**Comment by TimMoore** [comment]
Thanks for the feedback... it might be a couple of weeks before I have spare time to work on this, but I'll keep it on my todo list.

**Comment by TimMoore** [comment]
I gave this a shot and ran into a snag: my `.rubocop.yml` inherits from `.rubocop_todo.yml`. After copying the former, it couldn't find the latter.

Does anyone have any other ideas short of (recursively) parsing the YAML file and copying inherited files? I might have to resort to that. I guess that would require pulling in a YAML parser from NPM as a dependency. Would that be acceptable to the maintainers?

**Comment by szhu** [comment]
Here's another issue that doesn't translate to temporary files: excluding by filename.

Example: https://github.com/caskroom/homebrew-cask/blob/master/.rubocop.yml

**Comment by szhu** [comment]
Why do we save to a temporary file even with "Lint on the fly" turned off?

**Comment by caseywebdev** [comment]
We're not using temp files anymore, so this should work fine.
