### ISSUE TITLE
lint only on save?

### ISSUE THREAD

**Issue by bgentry** [AtomLinter/linter-rubocop#190]
Is there an option to lint only on save? The performance penalty and popups that happen when I'm actively writing code are a bit annoying. I'd like to run the linter less often.

**Comment by maschwenk** [comment]
Implemented in https://github.com/AtomLinter/linter-rubocop/pull/192

**Comment by Arcanemagus** [comment]
This is already implemented in the settings for Linter itself, which controls when these providers are executed. Assuming it even checks that variable more than the initial time, is this something that really should be done here?

Btw @bgentry in the Linter settings you can increase the delay it will wait before starting a lint when you are typing. I personally bump it from the default 300ms up to 1500ms.

**Comment by bgentry** [comment]
@Arcanemagus ahh, I was trying to find where such a setting would be and didn't know about the parent Linter package. Sorry for the wasted time =/

Maybe the settings screen of linter-rubocop could somehow make it clearer that there are many relevant settings located elsewhere?

**Comment by Arcanemagus** [comment]
Unfortunately Atom doesn't really have a way of specifying some text there, it's settings or nothing.
