### ISSUE TITLE
Prep linter-rubcop for v2 linters

### ISSUE THREAD

**Issue by maschwenk** [AtomLinter/linter-rubocop#196]
https://github.com/steelbrain/linter/blob/master/docs/examples/standard-linter-v2.md

**Comment by Arcanemagus** [comment]
Note that there is currently no way to ensure that a user is on v2 of linter, so updating to that version without a way to force v2 linter or at least without checking for it is probably going to end up causing problems.

I've yet to come up with a solution that I like, the best option I've got so far is adding support for forcing a version in `atom-package-deps`, or at the least doing a check on the version of `linter` loaded in Atom and exiting if it isn't new enough.

**Comment by maschwenk** [comment]
Looks like this got merged https://github.com/steelbrain/package-deps/pull/86 , so I don't need to worry about this?

**Comment by maschwenk** [comment]
How do you feel about current implementation here: https://gfycat.com/ScientificGrossBluebottlejellyfish

It's pretty much as is except the following:
1. Linter 2.0 allows for more granular error/refactor/info type of feedback, so I've mapped those out:
```
   {
      refactor: 'info',
      convention: 'info',
      warning: 'warning',
      error: 'error',
      fatal: 'error',
    }
```

**Comment by Arcanemagus** [comment]
You still need to somewhat worry about it, [This](https://github.com/AtomLinter/linter-rubocop/blob/95602160205360edfc75029f8a342d9d7ed73093/package.json#L46) need to be changed to `"linter:2.0.0"` 😉.

**Comment by Arcanemagus** [comment]
Is it linking, bundling, or dynamically pulling down those descriptions? I generally try to avoid bundling as that just means one more thing that you need to maintain in order to keep up to date. Dynamically pulling it down is a possibility with the new API, I'm not sure how much of a pain that would be though.

**Comment by Arcanemagus** [comment]
As for how it looks, I'll leave that to somebody that actually uses `rubocop` to determine whether it's useful or not 😛.

**Comment by maschwenk** [comment]
@Arcanemagus that's what I meant, it directly pulls it from the Github asynchronously when you expand that dropdown (with some caching potentially)
