### ISSUE TITLE
False positive: use snake_case for source file names on all ruby files

### ISSUE THREAD

**Issue by afarrell** [AtomLinter/linter-rubocop#2]
(Approximately) the first non-comment line of every ruby file is marked:

"Use snake_case for source file names"

 on all ruby files .

Regardless of whether the file is snake case, e.g. "foo.rb" or "foo_bar.rb".

Edited for formatting.

**Comment by MauPalantir** [comment]
I do have it either.

**Comment by shingonoide** [comment]
:+1: same here @arandaio 
Atom: 0.177.0
Linter: 0.11.1
Linter Rubocop: 0.2.1

**Comment by lolomet** [comment]
+1

**Comment by samtgarson** [comment]
+1 
Sublime 3 Build 3083

**Comment by marcusl33beach** [comment]
+1

**Comment by Arcanemagus** [comment]
@marcusl33beach Can you file a new issue? The linter has been completely re-written since this issue was filed, and no longer uses a temporary file in the first place...
