### ISSUE TITLE
Linter v2 + rubocop - execution timeout errors

### ISSUE THREAD

**Issue by joshfng** [AtomLinter/linter-rubocop#202]
![image](https://cloud.githubusercontent.com/assets/302764/24217045/de72dbe4-0f14-11e7-8d56-29f8aae47596.png)

linter 2.1.0
linter-rubocop 1.1.1

After upgrading to linter v 2.0+ the rubocop linter has become unusable on my system. My screen gets flooded with errors and it maxes out my CPU.

![image](https://cloud.githubusercontent.com/assets/302764/24217128/28569994-0f15-11e7-9e4d-be0ec3dec799.png)

I'm not sure exactly what's causing this yet. This didn't happen on the 1.x version of the base linter. Is it possible to tune the timeout options for the linter and to ensure it doesn't spawn too many processes at once?

**Comment by maschwenk** [comment]
I'm in the process of releasing linter-rubocop 1.2.0 which will directly hook into the new Linter 2.1.0 API

**Comment by Marahin** [comment]
@maschwenk it became an issue when I switched to JRuby projects (as JRuby takes some time to start). Cool option would be to be able to set timeout limit in settings or something. 
Apart from JRuby, it works perfect (I'm running mostly on 2.3.1+), thank you for your work!

**Comment by jpserra** [comment]
+1 for @Marahin comment, I have been getting this error a lot in JRuby projects. 

Would be happy to help you test if your current work fixes this issue @maschwenk !

**Comment by maschwenk** [comment]
You guys can test the new version doing the following:

1. Clone this repo
2. Inside the repo folder run `apm link --dev`
3. Start atom via `atom --dev .`

**Comment by jpserra** [comment]
Thanks! it's just missing the `npm install` there.

Don't wanna rush into conclusions but it seems that it is seems to me that the problem persists.

**Comment by joshfng** [comment]
As it currently is the insane amounts of process spawning causes my cpu to max out and fans to go full blast. I've had to disable both the rubocop and ruby linters to stop my computer from locking up for seconds at a time

**Comment by maschwenk** [comment]
Hey all, currently recovery from surgery so it's unlikely I can get a fix out soon, though I'm still a little uncertain what the fix would be. It [appears](https://github.com/steelbrain/linter/issues/1404) this is caused by Rubocop timing out after 10 seconds. I use the plugin every day and haven't run into the issue. I'm trying to think of reasons why Rubocop could _ever_ run for 10+ seconds

**Comment by joshfng** [comment]
Best wishes for your recovery!

I'm not sure what is happening for other people, but I think most of my problem is the interval that it runs as you type is causing a fork bomb. As I'm writing code, every 1/4 second or so it spawns a rubocop process to lint the file. This ends up spawning multiple rubocop instances while I type, which pegs the cpu. The timeouts are probably because the system is maxed out and nothing returns within 10 seconds. I'm on a last generation MPB and didn't have this issue until the v2 linter upgrade came.

**Comment by maschwenk** [comment]
Have you tried changing these values at all? 
![image](https://cloud.githubusercontent.com/assets/1264305/24629887/77bb451c-186f-11e7-9294-96ff94485817.png)

**Comment by Marahin** [comment]
>I'm trying to think of reasons why Rubocop could ever run for 10+ seconds.  

@maschwenk let me explain.
When you're using [JRuby](http://jruby.org/), if you run a script (`ruby something.rb`) the flow is fairly simple:
- JVM has to start alongside with Ruby interpreter,
- the code has to be interpreted and ran,
- JVM shutdown

The first step (JVM startup) takes couple of seconds on it's own. When we run Rubocop, it first takes couple of seconds to just startup JVM and load all the files, and then the Ruby code interpretation happens (which is fast, really).
Example to just show the issue:
```
$ ruby -v
jruby 9.1.8.0 (2.3.1) 2017-03-06 90fc7ab Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [darwin-x86_64]
```
The code:
```
$ cat test.rb
start = Time.now
puts "Hello world!"
finish = Time.now
puts "Code execution took #{finish-start} seconds"
```
Running it: 
```
$ time ruby test.rb
Hello world!
Code execution took 0.001274 seconds
ruby test.rb  6.57s user 0.32s system 249% cpu 2.762 total
```

So as you can see I ran the script. JVM & JRuby startup took (6.57-0.001274)seconds, whereas the Ruby code and it's execution took only 0.001274 seconds.

**It's not Rubocop**. It's the **JVM startup** that causes the linter to timeout. 

**Solution**:

I see two possible solutions:
* either check if current interpreter is JRuby (and not MRI ruby / Rubinius) - because that will tell you that the timeout has to be longer, because each time Rubocop is called - JRuby and JVM has to be started up,
* or allow us, users, to overwrite timeout on our own.

Thank you very much for your response and I hope I made the issue clearer now :)

**Comment by maschwenk** [comment]
@Marahin excellent explanation. The good ole JVM warmup! I remember that fondly (not so fondly from my days of working on J2EE apps ;) ). I will probably go for the latter option first, just for simplicity sake, and if that's working for you guys I can then maybe come up with more reasonable defaults.

**Comment by Marahin** [comment]
@maschwenk cool!
This should fix the issue for JRuby projects, however what's happening to @joshfng is probably something else (overutilization of CPU resources?) that I cannot reproduce.

**Comment by maschwenk** [comment]
Long term fix for a bunch of spawned processes appears to be documented here https://github.com/steelbrain/exec/issues/81

**Comment by Arcanemagus** [comment]
@maschwenk If you were interested, an alternative implementation to what is outlined in https://github.com/steelbrain/exec/issues/81 can be found [here](https://github.com/AtomLinter/linter-pylint/commit/d9d73c93dce324759e9411acdfc7fb7d48799ed8), it's somewhat untested though it "should" work.

**Comment by maschwenk** [comment]
I just deployed 2.0.0, which has the timeout configurable (as well as a lot of other changes https://github.com/AtomLinter/linter-rubocop/blob/master/CHANGELOG.md). Please let me know how it works for this (if it fixes your current problem and any other bugfixes 😉 )

**Comment by jpserra** [comment]
I've updated to the latest version, and I can confirm that the configurable timeout _solves_ the issue, although in my particular case I had to set it to 2 minutes. 

That being said, this is far from optimal so I'm gonna leave a workaround solution here I find best.

To solve this problem and have a performant rubocop linter in my atom in both `mri` and `jruby` projects I did the following in the console:

```shell
#On my home folder, installed latest ruby version
> rvm install ruby-2.4.1

#Installed the necessary gems
> gem install rubocop
> gem install rubocop-rspec

#Find the rubocop path
> which rubocop
/Users/<<you>>/.rvm/gems/ruby-2.4.1/bin/rubocop
```
After this, you just need to go to the `linter-rubocop` settings in Atom and replace the default `rubocop` command with the output of `wich rubocop` replacing `bin` with `wrappers` : ` /Users/<<you>>/.rvm/gems/ruby-2.4.1/wrappers/rubocop`. You should be all set afterwards.

**Comment by Marahin** [comment]
@maschwenk I think I forgot to mention it, but basicly what @jpserra has written above is - I believe - the most efficient solution. Using JRuby to run rubocop will take _far_ too long, so setting it static route to MRI ruby is the best. :-)

**Comment by nruth** [comment]
I'm having this problem with MRI and it links me to this closed issue. It's too bad the timeout setting has been removed.

**Comment by AlexWayfer** [comment]
> I just deployed 2.0.0, which has the timeout configurable (as well as a lot of other changes https://github.com/AtomLinter/linter-rubocop/blob/master/CHANGELOG.md). Please let me know if the configurable timeout fixes your issue. And please file other issues if you fine them, it's a big release!

I don't see such setting in the versions 2.2.3, neither a change log about its removing.

![image](https://user-images.githubusercontent.com/6510020/53401421-d1ed3a80-39c0-11e9-94ce-411b3baa67be.png)

**Comment by AlexWayfer** [comment]
Also, about `which rubocop`: each project has specific RuboCop configuration and bundled version, and I use `bundle exec rubocop` as you can see above. So, it's not a work-around for me. And I'm getting timeout errors at Atom launch.

**Comment by msourada** [comment]
I'm having this issue as well. No RVM or similar. 
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
$ rubocop -v
0.74.0

atom: 1.40.1
linter-rubocop: 2.4.2

Runinng rubocop from cmd on my project folder takes usually between 1 and 3 seconds.

**Comment by eri-b** [comment]
I'm still seeing this error as well. I've set the linter to run `on save`. 

![s 2020-07-28 at 10 28 59 AM](https://user-images.githubusercontent.com/15454217/88679183-2ec0b900-d0bd-11ea-8bad-bb2befad8ecc.png)

$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

rubocop -v
0.88.0
