### ISSUE TITLE
overlapping floating message 

### ISSUE THREAD

**Issue by krishnaghatti** [AtomLinter/linter-rubocop#216]
with the new version of atom 1.17.0, i see that the floating message is transparent and overlaps with the underlying text. attached is a screenshot for your reference.

<img width="653" alt="screen shot 2017-05-19 at 12 00 55 am" src="https://cloud.githubusercontent.com/assets/10704122/26217790/4518a412-3c26-11e7-99d8-fe6e83c5a496.png">

**Comment by Arcanemagus** [comment]
This is a theme issue, see https://github.com/steelbrain/linter-ui-default/issues/309 for more details. (Currently `material-syntax-dark` is known to be broken).
