### ISSUE TITLE
Style Guide Defaults Updated for PercentLitteralDelimiters

### ISSUE THREAD

**Issue by vizjerai** [AtomLinter/linter-rubocop#218]
https://github.com/bbatsov/ruby-style-guide/pull/563

```
Style/PercentLitteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
```

**Comment by Arcanemagus** [comment]
I think you meant to file this over on [Rubocop](https://github.com/bbatsov/rubocop) 😉.

This is just a wrapper around that.

**Comment by vizjerai** [comment]
Looks like the real issue was which ruby and rubocop was being ran. Thanks `rvm`
