### ISSUE TITLE
Crash when active tab is empty and file extension is rb

### ISSUE THREAD

**Issue by timvoet** [AtomLinter/linter-rubocop#22]
Uncaught Error: spawn /Users/tvoet/.rbenv/shims/rubocop ENOENT

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core
### Steps To Reproduce
1. Close Atom with an blank Ruby file as the active tab
2. Relaunch Atom from the working project directory
3. Atom restores to the active tab but with the error message that appears below
### Stack Trace

```
At events.js:85

Error: spawn /Users/tvoet/.rbenv/shims/rubocop ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by maschwenk** [comment]
Stale issue, if still a problem, drop a comment
