### ISSUE TITLE
[BUG] Segmentation fault(…)

### ISSUE THREAD

**Issue by mayuri-aquis** [AtomLinter/linter-rubocop#220]
I am getting the following error on saving a ruby file in atom.

```
/home/rdeveloper2/.atom/packages/linter/lib/linter-registry.js:177 [Linter] Error running RuboCop Error: /home/rdeveloper2/.rvm/gems/ruby-2.4.0@oneview/gems/json-1.8.6/lib/json/ext/generator.so: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```

Can anyone please suggest me how to resolve this?
I tried reinstalling json, rubocop and atom linter packages but none worked

Thanks in advance

**Comment by maschwenk** [comment]
I can't say for sure but this definitely looks a `json` gem issue and not a Rubocop or Linter-Rubocop issue. Have you searched the issues on https://github.com/flori/json?

**Comment by Arcanemagus** [comment]
This is definitely a crash in the `json` Gem and has nothing to do with this package (and as @maschwenk said, likely nothing to do with Rubocop either).

**Comment by mayuri-aquis** [comment]
But rubocop on my terminal works well. As well as I don't get any error from json gem in my application. Issue exists only in atom. I am not sure why the error is mentioning ruby version 2.0.0 when I am using ruby 2.4.0
`ruby 2.0.0p648 (2015-12-16) [x86_64-linux]`

**Comment by maschwenk** [comment]
How are you running it, i.e. how is your `rubocop` command defined in `command`?

**Comment by mayuri-aquis** [comment]
command is set to default i.e rubocop

**Comment by maschwenk** [comment]
@mayuri-aquis if you run `which rubocop` at your command line, what is the output? The steps outlined here may be helpful: https://github.com/AtomLinter/linter-rubocop#settings

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
