### ISSUE TITLE
linter-registry.js [sm]:137 [Linter] Error running RuboCop Error: Failed to spawn command 

### ISSUE THREAD

**Issue by kmf** [AtomLinter/linter-rubocop#225]
Atom : 1.18
linter 2.2.0
linter-rubocop 2.1.1

Getting this error in the console when I switch my default rubocop binary to cookstyle

![2017-07-17-10 24 21](https://user-images.githubusercontent.com/78700/28260253-75994fd2-6ada-11e7-97dd-f18c6d8cfb3e.png)

obviously the file exists.
![2017-07-17-10 26 05](https://user-images.githubusercontent.com/78700/28260261-7ff7f26c-6ada-11e7-90eb-1d4b3f5433ca.png)

And cookstyle is in my path
![2017-07-17-10 27 53](https://user-images.githubusercontent.com/78700/28260297-a923fb2c-6ada-11e7-8e64-fae2aaea13ff.png)

**Comment by maschwenk** [comment]
Can you include your current Rubocop `command` setting in Atom? This feels potentially OOS given you're using `cookstyle` but down to take a look

**Comment by kmf** [comment]
I have used the full path ... seems to have resolved the issue
```/opt/chefdk/bin/cookstyle```
