### ISSUE TITLE
Not end of world, but something changed (rbenv, rubocop path)

### ISSUE THREAD

**Issue by dgsan** [AtomLinter/linter-rubocop#229]
I use rbenv, and until this week I'd always left the rubocop command set to just `rubocop` and never had an issue.

Starting this week for some reason I've had to set it to the output of `rbenv which rubocop` instead (`/home/******/.rbenv/versions/2.3.4/bin/rubocop`).

I'm not sure this creates any problems exactly, but it seems weird. I can confirm that I don't have any odd `.profile`/`.bash_profile`/`.bashrc` things changed/happening.

My suspicion is that an update to something changed the environment Atom loads/runs when launched, but not completely sure.

**Comment by maschwenk** [comment]
The last release of this package was 3 months ago so I'm skeptical that that is the cause. You most likely upgraded your default ruby version to `2.3.4` but didn't re-run `gem install rubocop`

**Comment by dgsan** [comment]
Can confirm that that's not the case, my assumption isn't that anything in *this* package changed, but that something in Atom (or a dependency) elsewhere did.

**Comment by Arcanemagus** [comment]
How do you launch Atom? Generally things like `rbenv` only work if you close _all_ instances of Atom and launch Atom from a shell where it is configured/enabled.

**Comment by dgsan** [comment]
Previously things were configured in a way that I could launch atom from anywhere (GUI launcher, console, etc., and have things work as expected). I've now got it narrowed down to "something changed the environment my GUI apps launch with," as it now seems to be working again from the command line after log out/log in.

I'm going to close as I assume at this point it's definitely some kind of change specific to my system.
