### ISSUE TITLE
Error running Rubocop Error: Process execution timed out

### ISSUE THREAD

**Issue by TheJayWright** [AtomLinter/linter-rubocop#234]
I just started receiving the error yesterday in Atom.

I'm running Mac OS X.

Error running RuboCop Error: Process execution timed out at /Users/myuser/.atom/packages/linter-rubocop/node_modules/sb-exec/lib/index.js:89:18
(anonymous) @ /Users/myuser/.atom/packages/linter/lib/linter-registry.js:159

**Comment by gluons** [comment]
Me too. Also face this issue.

Running on **Atom 1.19.3** on **Kubuntu 17.04**

**Comment by gluons** [comment]
Oh! Maybe duplicate of #202.

I found the solution.
Just find the absolute path of `rubocop` by `which rubocop` and set it in settings.

**Comment by TheJayWright** [comment]
I tried that with no success, however I reinstalled the rubocop gem and reinstalled the Atom package and have had success.

**Comment by maschwenk** [comment]
Indeed a duplicate of #202 . I've had some thoughts in the past of ways to trap errors like these and suggest changing the rubocop path but never quite got to it

**Comment by maschwenk** [comment]
Indeed a duplicate of #202 . I've had some thoughts in the past of ways to trap errors like these and suggest changing the rubocop path but never quite got to it
