### ISSUE TITLE
There is a way to stop messages when opened folder does not have rubocop installed?

### ISSUE THREAD

**Issue by lisotton** [AtomLinter/linter-rubocop#24]
Hi, 

When working with a lot of RoR projects that some of them has rubocop gem and others not, when open some project that does not have rubocop, a lot of warnings are popped out, there is some way to prevent it?

Thanks.

**Comment by benogle** [comment]
For reference, our atom reporting shows that several hundred people hit this error a day.

Looks like it needs to be handled upstream: https://github.com/AtomLinter/Linter/blob/master/lib/linter.coffee#L126

The error can be caught and handled via [BufferedProcess::onWillThrowError](https://atom.io/docs/api/v0.182.0/BufferedProcess#instance-onWillThrowError)

**Comment by philipgiuliani** [comment]
Would be very nice to just ignore it if that happens. I have to disable this package in some of my projects where we dont use rubocop.

**Comment by TimMoore** [comment]
Yeah, I work with multiple projects. Some use Rubocop, others don't. I currently need to remember to manually enable or disable the Atom plugin when I switch projects.

Maybe it should only run (or have an option to only run) when there is a `.rubocop.yml` in the project directory?

**Comment by AsaAyers** [comment]
These screenshots are from `linter-php`, but it seems like the flow is:

![selection_040](https://cloud.githubusercontent.com/assets/324999/7952175/9ada60c4-097f-11e5-8d1b-66ab6e3f8432.png)

and then if you select "Partially" it just puts a warning at the bottom of your editor next time:

![selection_041](https://cloud.githubusercontent.com/assets/324999/7952160/688670b8-097f-11e5-9f22-4fba60f50462.png)

Is this not what's happening?

**Comment by TimMoore** [comment]
That is what happens, but with linter configured to run on save, it adds another warning banner on every save, so they continue to creep up my window until I go through and close them all.

**Comment by KevinSjoberg** [comment]
:+1: for fixing this. I just started working on a legacy project where Rubocop isn't present and every time I save a file the Rubocop linter complains about not finding the `rubocop` binary. I had to disable the Atom linter completely via `Linter: Toggle` to make it stop.

**Comment by Arcanemagus** [comment]
Wow, since this issue was filed almost every single part of the Atom linter ecosystem has changed. I'm going to mark this as closed, @KevinSjoberg can you please file a new issue detailing exactly what you are running into so it can be investigated?
