### ISSUE TITLE
I keep getting error messages and cannot find out how to fix them

### ISSUE THREAD

**Issue by Mehrunes-Dagon** [AtomLinter/linter-rubocop#240]
<img width="466" alt="screen shot 2017-09-14 at 9 04 21 pm" src="https://user-images.githubusercontent.com/29470415/30525781-2017016c-9bc2-11e7-8391-d610fbb5cfce.png">
<img width="577" alt="screen shot 2017-09-15 at 6 55 56 pm" src="https://user-images.githubusercontent.com/29470415/30525780-2015d5bc-9bc2-11e7-9e22-c0cd05e55d95.png">

**Comment by Mehrunes-Dagon** [comment]
I've tried updating and uninstalling and reinstalling.. Nothing

**Comment by maschwenk** [comment]
What do you have defined as the `Command` in the package settings?

**Comment by Mehrunes-Dagon** [comment]
<img width="525" alt="screen shot 2017-09-17 at 4 54 49 pm" src="https://user-images.githubusercontent.com/29470415/30526083-1566b332-9bc9-11e7-85a2-74747d05ac5d.png">

**Comment by maschwenk** [comment]
Few things:
1. You should update the package, I can tell it's out of date by that screenshot
2. I'm guessing if you run the command that's in your executable path and add `--version` you'll get a version that's different from the version of Rubocop you intend to be running that project. Basically, by running the rbenv method and using the global shim, you'll have a single *global* Rubocop (which might not line up with the given *projects* Rubocop version) for that given *ruby version*. This way you don't need to run `bundle install` to make sure that Rubocop is working. The other method is just pointing it to the `bundle` shim and then you'll need to bundle install when you move into a different project to get things working.

**Comment by maschwenk** [comment]
Were you able to resolve the issue?

**Comment by maschwenk** [comment]
Closing until response
