### ISSUE TITLE
Please allow caching.

### ISSUE THREAD

**Issue by envygeeks** [AtomLinter/linter-rubocop#249]
https://github.com/AtomLinter/linter-rubocop/blob/26d8b9aad2895b3893660c9137e6183fb52e4b21/src/index.js#L11

Please allow caching, 4 seconds for each run is a long time, caching can cut that in a quarter, and since Rubocop will know if a file has changed, I don't see why this is disabled?

**Comment by Arcanemagus** [comment]
@caseywebdev It looks like you added this back in https://github.com/AtomLinter/linter-rubocop/pull/72/commits/1c4282e0b79644f941d024b787689225ddb73f27, any idea why?

**Comment by caseywebdev** [comment]
Back when that change was made caching only worked on saved files, which made linting on the fly impossible. I don't know what the behavior is today.

**Comment by envygeeks** [comment]
This feels like the sledgehammer came down on a tack.  This is one place where configuration should have been considered well before convention considering how expensive it is to launch Rubocop, and how expensive it is to run on the fly, it also the sledgehammer coming down on the tack because the rest of us who are sensitive to slow-editors have to suffer because of the people who are used to their laptops trying to take off like a helicopter because AtomLinter is launching such an expensive tool after every edit.

It would be nice if I could enable caching.

**Comment by maschwenk** [comment]
@envygeeks coming on a little strong there, clearly @caseywebdev's intention was not to eat up resources. I'd like to look into this more deeply.

**Comment by vzamanillo** [comment]
We can't do this because Rubocop does not cache results from code which is piped in to `stdin`.

Rubocop [runner](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/runner.rb#L196).

```
    def cached_run?
      @cached_run ||=
        (@options[:cache] == 'true' ||
         @options[:cache] != 'false' &&
         @config_store.for(Dir.pwd).for_all_cops['UseCache']) &&
        # When running --auto-gen-config, there's some processing done in the
        # cops related to calculating the Max parameters for Metrics cops. We
        # need to do that processing and can not use caching.
        !@options[:auto_gen_config] &&
        # We can't cache results from code which is piped in to stdin
        !@options[:stdin]
     end
```
