### ISSUE TITLE
linter fails in cases where `--no-display-cop-names` is not a valid argument

### ISSUE THREAD

**Issue by waldnzwrld** [AtomLinter/linter-rubocop#257]
The module would not lint code citing the following error in Developer Tools

`Error running RuboCop Error: invalid option: --no-display-cop-names`

- RuboCop versions 0.51 - 0.52.1 (untested below 0.51) 
- Ruby 2.4
- linter-rubocop version 2.2.1

Removing https://github.com/AtomLinter/linter-rubocop/blob/master/src/index.js#L15 resolves the issue. I'm opening this issue to better understand the reason for including this flag and discuss whether this would be better set as an option in the package configuration or if it could be removed and set either on the executable path configuration or within the rubocop.yml file

![github 2018-01-17 23-04-31](https://user-images.githubusercontent.com/4338862/35085039-b411eeda-fbdb-11e7-993d-203c8b75385c.png)

**Comment by arsoedjono** [comment]
Hi there, I got the same issue with different credentials:

- RuboCop version: 0.50.0
- Ruby 2.3.0
- linter-rubocop version 2.2.1

**Comment by maschwenk** [comment]
@Arcanemagus many people run Rubocop pre `0.52` as they jump around new/old projects so we can't enforce that as the default regardless of whether its in `0.52`.

**Comment by waldnzwrld** [comment]
@Arcanemagus it must be the project version which is 0.51.0 

In the meantime, editing the index.js file as described above is allowing me to continue my work. Thanks for getting back to me so quickly.

> Of course RuboCop couldn't do this in any sort of sane manner and apparently that flag breaks old versions so it's sounding like the version will have to be checked and stored, with that flag being dynamically added if supported.

Sounds like a solid plan, as many people do jump from one project to the next where different RuboCop versions are set as dependencies.

**Comment by blimmer** [comment]
I'm seeing the same problem with Rubocop 0.49.1 (as expected). The reason we have to stick back a few versions is because we run rubocop within codeclimate. Their containers run behind the rubocop release schedule. 

A version check to only add this option for the versions that support it sounds like the way forward.

**Comment by Arcanemagus** [comment]
This should be fixed in v2.2.2, please let us know if not!

**Comment by kidbrax** [comment]
Still seeing this issue on v2.2.2
