### ISSUE TITLE
Potential large memory leak

### ISSUE THREAD

**Issue by isiahmeadows** [AtomLinter/linter-rubocop#269]
I work in a rather large Rails code base (100K+ of Ruby alone), and I normally have Rubocop enabled linting as I type. Thing is, over the span of a few hours of continuous use (usually about 4-8), I find the Atom Helper process reaches upwards of 1GB of memory and starts slowing down substantially. This memory is *not* reclaimed during idle times, and disabling the package fixed all my memory issues.

This only started happening with the latest release IIRC.

(This is on macOS High Sierra, on the newest MacBook Pro model.)

**Comment by Arcanemagus** [comment]
Are you able to look at a memory heap snapshot and see what is taking up all that room?

**Comment by Arcanemagus** [comment]
The only potential "large" memory usage I can see in the code that would persist between runs is the documentation. If you are using `linter-ui-default` that would only be being gathered if you expand the tooltips. If you are using `atom-ide-ui` they currently expand _all_ of them automatically... but even then it should only be one entry per rule name and I doubt there is more than a few MiB of documentation in the first place.

**Comment by isiahmeadows** [comment]
I'll do it next time it happens

**Comment by Arcanemagus** [comment]
> We could put the documentation fetch behind a config

It's a bug in `atom-ide-ui` that they are currently doing that, there's no reason for a configuration blocking that 😉.

**Comment by isiahmeadows** [comment]
BTW, I'm *not* using `atom-ide-ui` or anything related to it, so that's not the issue. I'll post back once it flares up again. (It doesn't repro frequently - I use Atom near-daily, and it only occurs about every 2-3 days.)

**Comment by isiahmeadows** [comment]
Here's a link to the snapshot (warning: it's about 300MB): https://drive.google.com/file/d/1dUO3TKzT2RyatGKDK6qHn-Da5QVmrBaS/view?usp=sharing

My RAM at the time was almost 900 right before I took it, so the snapshot doesn't seem to capture the whole story... (Either that or there's a memory leak in native code somewhere.)

**Comment by isiahmeadows** [comment]
Closing this as when I inspected a new (larger) heap snapshot, it's not pointing here.
