### ISSUE TITLE
Painfully slow performance

### ISSUE THREAD

**Issue by syedrakib** [AtomLinter/linter-rubocop#280]
Every line change and every cursor change runs rubocop and it stalls my editor for 2-3 seconds. I literally have to type on the editor blindly. It's gets very annoying at one point.

I disabled this specific package and my editor speed is back to normal.

**Comment by Arcanemagus** [comment]
This package is just a provider of a service to lint the files, it has _no_ control over when it actually gets ran.

If you are using `atom-ide-ui` unfortunately there is nothing you can do about this. If you are using `linter` you can either disable linting on change, which means it would only check when saving the file, or you can greatly increase the delay after you stop typing for it to automatically run. I believe the default is something like 200 ms, I personally set it to 1500 ms but you can pick whatever value you want 😉.

**Comment by syedrakib** [comment]
I confirm that the solution above is a pleasure indeed. Changed the settings in `linter` package and set  `Lint on Change Interval` to `2000` ms. Had to restart Atom once. It works well now. :) Thanks @Arcanemagus
