### ISSUE TITLE
Performance Cops will be removed from RuboCop 0.68

### ISSUE THREAD

**Issue by FunkyloverOne** [AtomLinter/linter-rubocop#309]
So this linter should be able to use `rubocop-performance` gem ~instead~ as well.

**Comment by Arcanemagus** [comment]
Is that a question or a statement?

You can customize the executable path, so as long as whatever you are pointing this at behaves like `rubocop` (same arguments, same output format) it should work just fine.

If it requires something different from `rubocop` it's probably better to fork this provider to a new one specifically for that.

**Comment by FunkyloverOne** [comment]
@Arcanemagus excuse me, I just saw that message during rubocop update and thought that it might be useful for `linter-rubocop` maintainers to know  ASAP :)

But now I've investigated, and we really can just modify command as shown [here](https://github.com/rubocop-hq/rubocop-performance#command-line):
```
rubocop --require rubocop-performance
```
Well, perhaps that could be a new default value? I find those performance hints quite useful sometimes :)

**Comment by vzamanillo** [comment]
@FunkyloverOne, thanks for the advice.

`rubocop-performance` is an extension, is not a Rubocop standard feature, we can not change the `linter-rubocop` behaviour due to the use of one and only extension, I think it's better to let the user configure the extensions using the `rubocop.yml` file as described [here](https://github.com/rubocop-hq/rubocop-performance#rubocop-configuration-file).

**Comment by Arcanemagus** [comment]
Closing as `wontfix` based on the above 😉.

**Comment by FunkyloverOne** [comment]
@vzamanillo the thing is - it used to be a part of rubocop out of the box (and it still is), and it will be removed from rubocop 0.68 because it can be now included as an extension.

So my point was that mentioning it in your README could help current and future users of this linter to preserve those now optional performance hints if they want it, as they always had it before out of the box.

**Comment by vzamanillo** [comment]
This linter does not manage Rubocop extensions, it simply executes Rubocop and show the results into the editor, as you said, `rubocop-performance` is used as part of Rubocop out of the box, so the mentions should be in the Rubocop's README, that info is redundant to place it here, is already on Rubocop's repository and every extension's README. In my opinion, if we include that info here will confuse the user even more in the proccess of setup the linter. Why to do an exception for a single extension and ignore the others (`rubocop-rspec`, `rubocop-thread_safety`... etc)?.

**Comment by FunkyloverOne** [comment]
@vzamanillo fair enough, agreed :)

**Comment by AlexWayfer** [comment]
If I don't want to use `rubocop-performance` — there is still warning in the RuboCop output and the linter fails. I think, it should be fixed.

**Comment by FunkyloverOne** [comment]
@AlexWayfer I believe that's only temporary RuboCop issue until 0.68. For now you could simply install `rubocop-performance` gem, and it won't be used after RuboCop update.

**Comment by AlexWayfer** [comment]
> @AlexWayfer I believe that's only temporary RuboCop issue until 0.68. For now, you could simply install `rubocop-performance` gem, and it won't be used after RuboCop update by default.

So, do you think, that it's better to change _every_ project, even these what don't need for `rubocop-performance`, instead of single fix for linter?

**Comment by Arcanemagus** [comment]
> If I don't want to use rubocop-performance — there is still warning in the RuboCop output and the linter fails. I think, it should be fixed.

I'd consider that a bug in `rubocop` that they did that in the first place (since the `json` shouldn't be corrupted with it!), however since they _did_, it should probably be handled here. Would you mind opening an issue to track that? Thanks!

**Comment by AlexWayfer** [comment]
@Arcanemagus, thank you! I got it. And I agree.

The PR with fix for RuboCop is created: https://github.com/rubocop-hq/rubocop/pull/6910

**Comment by vzamanillo** [comment]
Take a look at [this](https://github.com/AtomLinter/linter-haml/blob/master/lib/main.js#L80) on linter-haml, this is what we did to make the linter works with the `haml-lint` ruby parser warning messages.

**Comment by AlexWayfer** [comment]
Based on [this comment from RuboCop maintainer](https://github.com/rubocop-hq/rubocop/pull/6910#issuecomment-481753206), can `linter-rubocop` to capture only `stdout` (without `stderr`) from RuboCop?

**Comment by vzamanillo** [comment]
I am going to reopen this because needs some investigation, thank you @AlexWayfer

**Comment by vzamanillo** [comment]
@AlexWayfer, it fails with the latest `2.2.4 release`, it does not occurs with the current `master`, I think this was involuntary resolved on #301. @Arcanemagus could we make a new release?

**Comment by AlexWayfer** [comment]
> @AlexWayfer, it fails with the latest `2.2.4 release`, it does not occurs with the current `master`, I think this was involuntary resolved on #301. @Arcanemagus could we make a new release?

Sounds good! I'll wait for a new release. Thank you.
