### ISSUE TITLE
chruby - Unable to parse rubocop version from command output: .0.67.2 (note leading dot)

### ISSUE THREAD

**Issue by jm3** [AtomLinter/linter-rubocop#313]
# [Linter] Error running RuboCop
## Error: Unable to parse rubocop version from command output: .0.67.2     

(note extra leading . in the version)

Ruby commands like scss-lint and rubocop aren't working for me from within Atom plugins, in a very frustrating to debug way. I'm using chruby + zsh, which seems like it may be the problem in some way. I reviewed #247 but it didn't change the result. I've tried invoking rubocop using its full path **and** with alternatively with the full path to the `chruby-exec` wrapper, with the same ("Unable to parse rubocop version") result.

    % rubocop --version
    0.67.2 (latest)

    Atom version
    1.36.0 (latest)

I also opened [#243](https://github.com/AtomLinter/linter-scss-lint/issues/243) at linter-scss-lint. with my issues there, in case that's helpful.

_Update:_ setting my shell to bash with chsh and restarting Atom made no difference, so maybe Zsh isn't part of the problem.

**Comment by vzamanillo** [comment]
I think this is related to #309, could you please try with Rubocop 0.66 or below? what linter version are you using? the latest release or did you a checkout from the current `master` branch?

**Comment by jm3** [comment]
@vzamanillo Thanks! It turned out that it was a few different things — the latest version of rubocop was **not**, in the end the problem, as my setup now works with both 0.66 and 0.67.2

The issue was that my shell dotfiles had an echo in them 🤦‍♂️ 

Now I have to figure out why linter-scss-lint still won't work :)
