### ISSUE TITLE
Atom doesn't inherit $PATH

### ISSUE THREAD

**Issue by nokutu** [AtomLinter/linter-rubocop#33]
When you open Atom not from the command line, it doesn't inherit PATH. This means that it won't have access to RVM things. The only way I found to solve this was, or just using the command line, or installing a system ruby version with rubocop.

I think that readme should be updated.

**Comment by DarthSim** [comment]
Probably you just need to set `executablePath` option.

**Comment by sheedhet** [comment]
I was able to fix this by changing my `executablePath` from:
```
"linter-rubocop":
  executablePath: "~/.rvm/gems/ruby-2.2-head/bin/rubocop"
```
to:
```
"linter-rubocop":
  executablePath: "~/.rvm/gems/ruby-2.2-head/wrappers/rubocop"
```

**Comment by vassyz** [comment]
I was going to give up, until I found this thread. Replacing ```bin``` with ```wrappers``` in the path fixed the issue for me. Maybe it should be mentioned somewhere in a Troubleshooting section.

**Comment by Arcanemagus** [comment]
Submit a PR for it @vassyz :wink:

Since it seems this is an issue with how the system finds `rubycop` and not this package I'm marking this as closed.
