### ISSUE TITLE
Rubocop 0.72.0 changes documentation URL breaking specs

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-rubocop#349]
It seems that between [these](https://travis-ci.org/AtomLinter/linter-rubocop/jobs/550031144) [two](https://travis-ci.org/AtomLinter/linter-rubocop/jobs/550375406) builds Rubocop 0.72.0 was released which changes the documentation URL over to `https://rubystyle.guide`, breaking the specs.

**Comment by vzamanillo** [comment]
Yep, I am waiting to release the PR #346 which already include a fix for that.
