### ISSUE TITLE
Error running RuboCop - Layout errors

### ISSUE THREAD

**Issue by TechFounder** [AtomLinter/linter-rubocop#353]
Not sure why I'm getting these layout errors after updating `.rubocop.yml` file with new layout definitions. Here's what the console says:

```
Error running RuboCop Error: 
Warning: unrecognized cop Layout/IndentFirstArgument found in .rubocop.yml
Warning: unrecognized cop Layout/IndentFirstArrayElement found in .rubocop.yml
Warning: unrecognized cop Layout/IndentFirstHashElement found in .rubocop.yml

Error: invalid EnforcedStyle 'indented_internal_methods' for Layout/IndentationConsistency found in .rubocop.yml
Valid choices are: normal, rails
```

Everything passes when I run the rubocop tests but for some reason, the linter is giving me errors.

**Comment by vzamanillo** [comment]
Looks like your rubocop config is not correct at all, look at https://rubocop.readthedocs.io/en/stable/configuration/ and https://rubocop.readthedocs.io/en/stable/cops/

I am closing this issue because is not directly related to this linter.

**Comment by TechFounder** [comment]
The config file should be correct as the newest version 0.72.0 uses these Layout settings. I even ran the mry gem to migrate the file. Not sure why your linter would show these errors?

**Comment by TechFounder** [comment]
This is weird, all of a sudden it's not giving errors and I didn't change a thing!? Wow.

**Comment by vzamanillo** [comment]
Paste your config file, please.

**Comment by TechFounder** [comment]
require: rubocop-rspec
AllCops:
  Exclude:
    - 'bin/yarn'
    - 'bin/spring'
    - 'db/schema.rb'
    - 'config/puma.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'vendor/bundle/**/*'
  DisabledByDefault: true

Layout/AccessModifierIndentation:
  Enabled: true

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/DotPosition:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/IndentFirstArgument:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/IndentationWidth:
  Enabled: true

Layout/IndentFirstArrayElement:
  Enabled: true

Layout/IndentAssignment:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: true

Layout/IndentHeredoc:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/Attr:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: true

Lint/Debugger:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true
  AutoCorrect: false

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

Bundler/InsecureProtocolSource:
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

Bundler/OrderedGems:
  Enabled: false
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

**Comment by TechFounder** [comment]
Thanks but what I don't understand is why even though my rubocop runs perfectly with no errors the linter keeps telling me that I do?

**Comment by TechFounder** [comment]
Thanks but as far as I can tell, everything in the config file is correct. I am also running rubocop-rspec as an extention. If there is something wrong with the config then running rubocop would give be errors as well. It runs perfectly `131 files inspected, no offenses detected`. So, I'm not sure what the problem is? I eve tried reinstalling your linter.

**Comment by vzamanillo** [comment]
Are you sure you are running the same Rubocop version on console and on the linter?

**Comment by TechFounder** [comment]
Not sure what you mean? I'm running:
```
rubocop -v
0.72.0
```
and the linter is 2.4.2. Is there something I'm missing?

**Comment by vzamanillo** [comment]
Where is that Rubocop binary located? Is that the one and only version instaled on your machine? Is that version the same version that linter runs?

**Comment by TechFounder** [comment]
As far as I know, I'm only running one Rubocop binary. As far as the linter is concerned, how are you able to specify the version you want to run? In my `config.cson` Atom file, I see that the linter 
```
  "linter-rubocop":
    disableWhenNoConfigFile: true
```
and that's the only setting listed for Rubocop. I thought that the linter will run whatever version you have in the system?

**Comment by vzamanillo** [comment]
I was running the atom-linter on my environment with your `.rubocop.yml` configuration settings and no problem at all. I think you are running a Rubocop version older then 0.72.

To know where is your Rubocop binary, from console, execute `which rubocop`, to know what Rubocop binary is used by the linter goto to `Atom menu -> Packages -> Settings view -> Manage packages` and search for `linter-rubocop`

**Comment by TechFounder** [comment]
which rubocop
`/.rvm/gems/ruby-2.6.3/bin/rubocop`
 in the linter `Default: rubocop`

**Comment by vzamanillo** [comment]
Try using that path as linter-rubocop command, please.

**Comment by TechFounder** [comment]
ok, now I'm getting:
`Error running RuboCop Error: spawn EACCES`

**Comment by TechFounder** [comment]
ok, it looks like I have to use /wrapper instead of /bin

Still, not sure why all of a sudden I have to enter the linter-rubocop path? The default always worked. Thanks for your help!

**Comment by TechFounder** [comment]
Hi, I have a question. Do you know how to set the rubocop to be global? It looks like the reason I was getting the errors was as you suggested, that the linter was using a different version. The question I have is how do I find the version that the linter is using and just update that? Because using RVM with different version would mean that will have to change the path in the linter settings each time that I change the ruby version with RVM. There must be an easier way? Is there a syslink that I can use so that it uses the default setting in the linter?

**Comment by vzamanillo** [comment]
You can setup a default global ruby version with `rvm --default use 2.3.6`, check the `rvm` docks at https://rvm.io/rubies/default

**Comment by TechFounder** [comment]
Thanks, I did look into that but as far as I can tell, that only sets the default rubocop for one ruby version and all of the gemsets that are within that one version? If you switch to another ruby version you'll have to change the path?

**Comment by vzamanillo** [comment]
You can setup one and only default version with `rvm`, yes, if you want to use Rubocop with another Ruby version you'll have to change the Rubocop path.

**Comment by TechFounder** [comment]
Thanks, I thought that I may be missing some installation method that would allow me to install Rubocop in just one place such as /usr/local/bin so that it doesn't matter which ruby version I use. I guess not.
