### ISSUE TITLE
 Cannot read property 'stdout' of null

### ISSUE THREAD

**Issue by souljuse** [AtomLinter/linter-rubocop#366]
Hi! I am currently getting this error when I save any .rb file.

Rubocop: Parse error
Cannot read property 'stdout' of null

The package works as expected when I disable the "Fix error on save" option.
Could you help me?

**Comment by vzamanillo** [comment]
Hi! I can't reproduce the error with the latest release nor the latest master branch.

Could you please tell me your current plattform (mac, win, nix), Rubocop and linter-rubocop version?

**Comment by souljuse** [comment]
Here are the versions: I attach a gif of the error
linter-rubocop 2.5.2
rubocop 0.76.0
rbenv 2.5.1
MacOS Mojave 10.14.6

About linter-rubocop config: I am using bundler and auto save

![2019-11-06 12 12 02](https://user-images.githubusercontent.com/13051823/68293662-b6c5e500-008e-11ea-9cc9-d5d7f417fb7e.gif)

**Comment by vzamanillo** [comment]
Confirmed, thank you, a temporal workaround is uncheck the `Disable when no .rubocop.yml config file is found` configuration option.

**Comment by souljuse** [comment]
Thanks :)
