### ISSUE TITLE
Rubocop Executable Path shows up two times in settings

### ISSUE THREAD

**Issue by Eschon** [AtomLinter/linter-rubocop#41]
On Atom 0.201 and linter-rubocop 0.2.7

When I started Atom I got notified that the rubocop executable was not found. When I checked the settings I found that there are two fields for the path.

![screen shot 2015-05-22 at 14 20 55](https://cloud.githubusercontent.com/assets/11647830/7770352/d042f992-008d-11e5-99ec-3fbc8a8c3be1.png)

I set the path in the empty field but linter-rubocop still does nothing.

**Comment by TimMoore** [comment]
Seems to be fixed in the latest version of Atom

**Comment by adammw** [comment]
Still present for me on Atom 0.207, along with an error message that the executable for rubocop can't be found.

**Comment by joshminnie** [comment]
Still present for me on Atom 0.211.0 and linter-rubocop 0.2.7

**Comment by Eschon** [comment]
If this still happens for you open your config.cson remove all lines from linter-rubocop and reload your settings view. Now there should be only one entry and you can put your executable path there.
