### ISSUE TITLE
Unnecessary running lint on .erb

### ISSUE THREAD

**Issue by amerov** [AtomLinter/linter-rubocop#437]
I have installed rubocop and erb linters.
linter-erb doesn’t work if it has opened only .erb files.
if it has separately opened .rb files then it lint erb with ruby linters.
Screencast: https://www.youtube.com/watch?v=uJMF8GOYKV8

UPD: It works if syntax changed to erb without tree-sitter
## Environment
 - OS: Manjaro Linux x86_64
 - Atom version: 1.52.0
 - linter-rubocop version: 2.5.7
 - Ruby version manager: chruby
 - Rubocop version: 0.88.0

**Comment by vzamanillo** [comment]
dup #48
