### ISSUE TITLE
Linter rubocop not linterting. 

### ISSUE THREAD

**Issue by aecorredor** [AtomLinter/linter-rubocop#44]
As the title says it, simply nothing happens as I type code. I tried most troubleshooting tips that you can find out there. Modifying cson file, uninstalling everything (including atom), opening from terminal, etc. Any help appreciated. thank you.

**Comment by consti** [comment]
my linter-rubocop failed silently because I had this extra line in my config.cson:

```
"linter-rubocop": {}
```

that just overloaded my previous settings. Removing the line helped. Maybe you missed that one?

**Comment by aecorredor** [comment]
Hey thanks for answering. Unfortunately I did remove that line. I have the right executable path, and I am getting no errors whatsoever.

**Comment by untra** [comment]
I am also having this problem on a few of my machines. I've gotten linter-rubocop to work on a few machines, and I've seen it fail quietly like @aecorredor is mentioning on others. I'll see if I can find a clue between the installations.

**Comment by THPubs** [comment]
Same issue here. The linter does not work anymore.

**Comment by consti** [comment]
For me, it helped to remove `linter-rubocop` from Atom (just clicking uninstall in the packages menu), then reinstall (in the packages menu), then check your config.cson and remove `"linter-rubocop": {}`.

**Comment by aecorredor** [comment]
Hey guys, thanks for all the responses. I've tried @untra 's solution of running gem install rubocop, apm install linter, and apm linter-rubocop, and checking my exec. path and it is still not working. Also tried @consti 's solution, did not work either. My executable is /Users/Alejandro/.rvm/gems/ruby-2.2.1/bin/rubocop, I use the parent directory /Users/Alejandro/.rvm/gems/ruby-2.2.1/bin/ as the exec. path. Hope somebody else gets lucky. Let me know if you guys find a fix. Cheers.

**Comment by Riddlerrr** [comment]
+1 @aecorredor
Linux, atom 0.209
`config.cson`:
```
"*":
  editor:
    fontSize: 13
    invisibles: {}
    showInvisibles: true
    softWrap: true
    scrollPastEnd: true
  core:
    themes: [
      "atom-dark-ui"
      "atom-dark-syntax"
    ]
    ignoredNames: [
      ".git"
    ]
  "exception-reporting":
    userId: "4ef8ea16-af2d-d3bc-92f9-773e591398f8"
  welcome:
    showOnStartup: false
  "bracket-matcher": {}
  "save-session":
    dataSaveFolder: "/home/riddler/.atom/packages/save-session/projects"
  minimap: {}
  linter: {}
  "linter-rubocop":
    executablePath: "/home/riddler/.rvm/gems/ruby-2.1.3@alloka/bin"
```

rubocop work fine in terminal

**Comment by Riddlerrr** [comment]
I try `linter-ruby`. It work fine for me. What's wrong with `linter-rubocop`?

**Comment by esilverberg** [comment]
+1 I cannot get linter-rubocop working. I uninstalled everything and reinstalled via apm. I am running OSX Yosemite with Atom 0.210.0. linter-rubocop was the only reason I was using atom; I could never integrate it successfully with any other text editor.

**Comment by THPubs** [comment]
Did you check the rubocop config file? If you are using a custom config, check it for errors. Even a stray white space can cause issues.

**Comment by esilverberg** [comment]
It is somehow related to the presence of a .rubocop.yml file! If I have a blank .rubocop.yml file, it will not work in Atom; but when I remove the file it works. Originally my file was not blank and had valid exceptions in it. There must be some kind of regression parsing the .rubocop.yml file, either in rubocop, linter-rubocop, or both.

**Comment by jrissler** [comment]
+1 couldn't get working here either - tried previous steps other people had suggested.

**Comment by aecorredor** [comment]
bump. If anyone in the discussion found a solution please let us know. thanks.

**Comment by cirdes** [comment]
After linter last update(1.0.4), linter-rubocop is now working properly here.

**Comment by jrissler** [comment]
@cirdes confirmed here - good now also :+1:

**Comment by aecorredor** [comment]
Still not working for me...already updated everything. I don't know if there is something essential that I am not doing. It is suppose to lint as soon as I start typing in an rb file right? with ruby set as writing language too obviously right?

**Comment by khelll** [comment]
+1 not working for rvm yet.

**Comment by aecorredor** [comment]
So I found a fix, at least for me. I was using rvm before and I just switched to rbenv and now it's fully working. I guess if you don't mind not using rvm this is fine. cheers.

**Comment by kieranklaassen** [comment]
+1 not working with RVM for me too

**Comment by sheedhet** [comment]
I was able to get it working with RVM on OS X:

I was looking for an alternative [when I found a clue here,](https://github.com/yujinakayama/atom-lint#installation) I guess there's a problem with PATH and Atom needs to be opened via the command line at least once. I used the ```atom``` command from the app directory to launch the app, and now linter-rubocop is working. Wow that was frustrating!

**Comment by kieranklaassen** [comment]
@sheedhet That solves it for me too. Although it would be nice to have it working without opening the atom with the directory via the terminal. :+1:  Thanks!

**Comment by khelll** [comment]
@sheedhet yes worked for me.

**Comment by mereghost** [comment]
Opening from the command line works fine, but IMO is a very lame workaround. =(

**Comment by consti** [comment]
This is a known issue with atom-lint and thus probably with linter: https://atom.io/packages/atom-lint#linter-executable-paths

I had to add the path to my rubocop file to the PATH variable in the atom init script.

**Comment by mneumark** [comment]
@sheedhet Worked! Thanks! Now I don't feel like I'm going crazy!
@hd-deman Any chance of a fix some time soon?

**Comment by esilverberg** [comment]
FYI linter 1.3.0 seems to have broken it for me -- I downgraded back to 1.2.4 and it worked again.

**Comment by Eschon** [comment]
@esilverberg linter 1.3.0 removed a deprecated api that was still used by linter-rubocop. Until linter-rubocop switches to the new api you need to stay on 1.2.4 for it to work.

**Comment by infernalsirius** [comment]
It's working for me if I start it from the command line. Otherwise it's giving me errors.

**Comment by ssummers1** [comment]
Removed the line `linter: {}` from config.cson then it worked for me.
