### ISSUE TITLE
Rubocop command is not found.

### ISSUE THREAD

**Issue by Arunk1390** [AtomLinter/linter-rubocop#47]
[Enter steps to reproduce below:]

    ...
    ...

Atom Version: 1.0.0
System: Linux Mint
Thrown From: Atom Core
Stack Trace

Rubocop command is not found.

At When you don't install rubocop yet, Run `gem install rubocop` first.

If you already installed rubocop, Please check package setting at `Rubocop Command Path`.

undefined

Commands

Config

{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "ruby-slim",
      "ruby-slim",
      "ruby-slim",
      "linter"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true
  }
}

Installed Packages

# User
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
rubocop-auto-correct, v1.0.0

# Dev
No dev packages

**Comment by perlun** [comment]
Have you tried doing what it tells you, i.e. `gem install rubocop`?

**Comment by greyfellow** [comment]
hello, I have the same issue, I've installed the linter the command was there I've used it one time then it just disappeared! I just don't know what happened !! I tried to uninstall and install the plug-in many times but it didn't work.

**Comment by Arcanemagus** [comment]
@greyfellow What do you get from running the following in a terminal / command prompt:
* If you are on Linux / OSX: `which rubocop`
* If you are on Windows: `where.exe rubocop`

**Comment by greyfellow** [comment]
after running `which rubocop` it gave me this "/usr/local/bin/rubocop", and its the path I am using in the plugin settings. I use rbenv and I am on Ubuntu 14.04. my question is does the linter come with a commande to apply rubocop on files or does it just lint the file because for the linting part I have no issue ? and forgive me I miss understood the issue I am having :disappointed:

**Comment by Arcanemagus** [comment]
This package runs `rubocop` on the currently open file(s), transforms the output into a format the `linter` package understands, and sends those messages off to it for display.

Are you getting an error message every time you edit/save the file saying `rubocop` isn't found or... what?

Also generally when using `rbenv` you need to create a wrapper script as it usually relies on shell macro scripts to work properly... which only work when running from a shell and not when run from in a program.

**Comment by greyfellow** [comment]
after trying again everything works well actually everything was already well it is me who didn't understand fully the workings of the `linter`, I apologies for this miss understanding and thanks a lot guys for the explanation :).

**Comment by Arcanemagus** [comment]
Glad to hear you got it figured out :wink:.
