### ISSUE TITLE
Rubocop being run against erbs

### ISSUE THREAD

**Issue by baxter** [AtomLinter/linter-rubocop#48]
Recently I've started experiencing a problem where linter-rubocop runs rubocop against erb files.

Running `rubocop` from the command line, erb files are skipped as expected.

Is this a known problem? If so is there any workaround for it? I tried adding `app/views` to the list of excluded files, but I suspect rubocop ignores this when linter-rubocop passes in the filename explicitly.

Thanks,

Paul.

**Comment by SxDx** [comment]
I also have this Problem but I'm not sure which update introduced it.

**Comment by jensljungblad** [comment]
Have this as well. Is it possible to work around until a fix is made available?

**Comment by aar0nr** [comment]
A workaround is to switch the language of the file to ```HTML (Rails)``` instead of ```HTML (Ruby - ERB)```, and then reopen the file.

**Comment by Project0** [comment]
seems to be an problem with the language-ruby plugin. 
same problem like in linter-ruby. https://github.com/AtomLinter/linter-ruby/issues/26

**Comment by davidchristiandy** [comment]
Or, you can exclude .erb extensions (for now) by adding it to your exclusion list. Here's a snippet of my `.rubocop.yml`:

```yml
AllCops:
  ...
  Exclude:
    - '*.erb' # add this.
...
```

**Comment by nickpoorman** [comment]
+1

**Comment by Arcanemagus** [comment]
As mentioned over in https://github.com/AtomLinter/linter-ruby/issues/26 this is a bug in `language-ruby`, you can try installing `language-ruby-on-rails` which properly marks embedded ruby code as `source.embedded.ruby`, which this plugin (correctly) does **not** mark itself as being able to handle.

I'm marking this as closed since this isn't an issue that can or should be fixed here.

**Comment by Arcanemagus** [comment]
Filed an issue over there as it seems nobody had bothered to yet :wink:.

**Comment by rutgerfarry** [comment]
@Arcanemagus could this issue be opened again until it's fixed? It seems the requested scope changes were made in atom/language-ruby#114, but the linter still attempts to run against .html.erb files

**Comment by Arcanemagus** [comment]
@rutgerfarry This issue has been fixed since Atom v1.4.0-beta0. If you are still experiencing this can you file a _new_ issue with the scopes you are seeing when you run `Editor: Log Cursor Scopes`?

**Comment by vzamanillo** [comment]
I am experiencing this issue, first time, after upgrading Atom

**Software versions:**

Ubuntu 18.10
language-ruby: 0.72.14
language-ruby-on-rails: 0.25.3
linter-ruby: 1.2.6
linter-rubocop: 2.2.3
Rubocop: 0.60.0
Atom: 1.32.2

**.rubocop.yml**


```
AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Style/AsciiComments:
  Enabled: false
```

**Comment by RonaldDijkstra** [comment]
Me too!

**Comment by PetrKaleta** [comment]
Same here, happening again with:

```
Atom 1.33.0
linter 2.2.0
linter-rubocop 2.2.3
language-ruby 0.72.14
language-ruby-on-rails 0.25.3
```

**Comment by vdhpieter** [comment]
Same here:
```
Atom 1.33.0
linter 2.2.0
linter-erb 1.1.1
linter-rubocop 2.2.3
linter-ruby 1.2.6
language-ruby 0.72.14
language-ruby-on-rails 0.25.3
```

Can you reopen this issue?

**Comment by meap** [comment]
+1

**Comment by RonaldDijkstra** [comment]
Do you guys maybe know how to ignore erb files at all?

**Comment by RonaldDijkstra** [comment]
```ruby
AllCops:
  Exclude:
    - "**/*.erb"
```

Putting this in `.rubocop.yml` fixed this issue for me.

**Comment by vdhpieter** [comment]
@RonaldDijkstra for me not really option as I share my config with my team :-(

**Comment by vdhpieter** [comment]
I digged a bit deeper here and found that it is broken because of a rubocop update related to this issue https://github.com/rubocop-hq/rubocop/issues/4666. It breaks on rubocop 0.56.0

**Comment by vdhpieter** [comment]
I think what happened here is that this line prevented rubocop from parsing a `.erb` file in the old versions:
https://github.com/AtomLinter/linter-rubocop/blob/9492d9b167a4943b662258af9beb1ceb382b2c6e/src/index.js#L231

But after the change the value of the `-stdin` does not have an effect anymore. So the real issue here is the same as before I guess to make sure a `.erb` file is not marked as a ruby file

**Comment by ahukkanen** [comment]
Same thing happening here.

This provides a remediation but does not fix the underlying issue:
https://github.com/AtomLinter/linter-rubocop/issues/48#issuecomment-443648075

**Comment by amerov** [comment]
it happens again :crying_cat_face: 
![atom-linter-erb](https://user-images.githubusercontent.com/196747/89137070-108d0a00-d550-11ea-84d6-1b391d904569.png)

**Comment by tony-rowan** [comment]
> ```ruby
> AllCops:
>   Exclude:
>     - "**/*.erb"
> ```
> 
> Putting this in `.rubocop.yml` fixed this issue for me.

>  for me not really option as I share my config with my team :-(

You can add it to a personal config file at `$HOME/.rubocop.yml` that way it won't conflict with your project / team. Not a perfect solution but it's workable work around.
