### ISSUE TITLE
"The linter binary 'rubocop' cannot be found." error

### ISSUE THREAD

**Issue by danielbayley** [AtomLinter/linter-rubocop#49]
It works if I manually add `/Users/Dan/.gem/ruby/2.0.0/bin/rubocop` absolute path under Settings (i.e to `config.cson`, but why when all of the other `linter-` packages find the `$GEM_HOME/bin` directory just fine as it is in my `$PATH` (and I know that Atom sees my $PATH because as mentioned, other packages that rely on it work fine).

OS X Yosemite 10.10.4
Atom 1.0.0
linter 1.1.0
linter-rubocop 0.2.7

**Comment by mbajur** [comment]
Same for me. It happens actually with all the other ruby-related linters (like linter-slim for example). It maybe might be something related to RVM ?

**Comment by danielbayley** [comment]
Well FYI, I don't use RVM so probably not.

**Comment by danielbayley** [comment]
After a lot of digging it seems that Atom itself still has trouble with `PATH` and that was causing this.
