### ISSUE TITLE
Doesn't work on Atom 1.0.0

### ISSUE THREAD

**Issue by andrefreitas** [AtomLinter/linter-rubocop#51]
I have installed linter-rubocop and gave the rubocop path and it is not working on Atom 1.0.0. I am using linter-ruby alternatively.

**Comment by Eschon** [comment]
Are you by any chance using OS X because than it could be related to #44 
The workaround for now is to start Atom from the command line.

**Comment by andrefreitas** [comment]
Yes is OS X

**Comment by ypresto** [comment]
I have same issue.
I tried below but nothing solves issue.

- Launch from command line
- Remove .rubocop.yml
- Set rubocop path in preference
- Disable linter-ruby

**Comment by afurm** [comment]
Doesn't work for me.

**Comment by mneumark** [comment]
The only way to get it to work is to open Atom from the command line with the file you are interested in getting linted with rubocop. Which is useless....
