### ISSUE TITLE
Settings option to specify path to `config.yml`

### ISSUE THREAD

**Issue by danielbayley** [AtomLinter/linter-rubocop#53]
…in a custom location.

**Comment by caseywebdev** [comment]
In `v0.3.1` you can use the additional arguments configuration option to set `-c /my/custom/config.yml`

**Comment by danielbayley** [comment]
Cool. Can that be a relative path (like `~/my/custom/config.yml`)?

**Comment by caseywebdev** [comment]
The `rubocop` command is run from the file's directory, so relative paths would not be reliable. Using the `~` home directory shortcut might work but I haven't tried. Worst case you'll have to use something like `/Users/danielbayley/my/custom/config.yml`.
