### ISSUE TITLE
Not working with linter@1.3.0

### ISSUE THREAD

**Issue by opsidao** [AtomLinter/linter-rubocop#56]
It works flawlessly with linter@1.2.4, but  when using 1.3.0 it just does nothing, no errors are reported and only a deprecation is shown as per #50.

If there is some way I can help debug it please let me know, I'm not really very up to date with developing (and debugging) for Atom, but the developer tools' console doesn't show any error.

I'm running on OSX Yosemite (10.10.3) with various ruby versions (all showing the same behavior) installed with rbenv.

**Comment by steelbrain** [comment]
It's because the depreciated API has been completely removed in that version of linter and this package hasn't upgraded yet :(

**Comment by opsidao** [comment]
Escuse me if it sounds stupid, but can't an atom package define version requirements on its dependencies? (just coming from a bundler background and wondering)

**Comment by steelbrain** [comment]
@opsidao Atom does have a way of defining dependencies like that, the future APIs of the linter will be backward compatible, but this linter was using a hack to work around dependencies, a hack which has been deprecated for more than a month and then removed at the end.

**Comment by opsidao** [comment]
Thanks for the explanation @steelbrain, and keep up the good work! ;)
