### ISSUE TITLE
Error popup on each Rubocop run

### ISSUE THREAD

**Issue by TimMoore** [AtomLinter/linter-rubocop#61]
Ever since updating to the latest version of `linter-rubocop`, this error pops up on each save:

![screen shot 2015-08-10 at 11 30 46 am](https://cloud.githubusercontent.com/assets/44385/9158042/5c760d74-3f53-11e5-8243-abbb611498fc.png)

```
Error: warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
{"metadata":{"rubocop_version":"0.32.1","ruby_engine":"ruby","ruby_version":"2.1.5","ruby_patchlevel":"273","ruby_platform":"x86_64-darwin14.0"},"files":[{"path":"../../../../../../var/folders/0_/w17vx8mx5kvgqzhbd59d06qm0000gn/T/69387008a68292900467c23649af55cd91149aacf3403caf7d602e1c7f15c4d4","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}
  at /Users/tim/.atom/packages/linter-rubocop/index.coffee:42:27
  at FSReqWrap.oncomplete (fs.js:77:15)
```

I get the same warning running rubocop from the command line, but it never previously appeared as an error popup in the editor.

It looks like the latest version of the plugin tries to append stderr to stdout and parse the entire thing as JSON. I suppose that's what triggers the internal error in Atom.

https://github.com/AtomLinter/linter-rubocop/blob/master/index.coffee#L39
https://github.com/AtomLinter/linter-rubocop/blob/master/index.coffee#L41

**Comment by TimMoore** [comment]
If I comment out the `stderr: appendToOut` line, it suppresses the error. Is there a reason stderr needs to be captured?

**Comment by doughsay** [comment]
The rubocop linter has completely stopped working for me too.  This is just a warning from rubocop that can safely be ignored.  No reason it should prevent the plugin from running at all.

**Comment by dannytip** [comment]
I'm getting the same error.  As its on every run it makes this plugin unusable.

**Comment by johnmeehan** [comment]
Not working for me either.   I've become too reliant on this package to change my ways :)

**Comment by afurm** [comment]
the same to me. Doesn't work.

**Comment by guitarman** [comment]
Same issue here
