### ISSUE TITLE
FSReqWrap.oncomplete error

### ISSUE THREAD

**Issue by dannytip** [AtomLinter/linter-rubocop#65]
Error
  at ~/.atom/packages/linter-rubocop/index.coffee:45:27
  at FSReqWrap.oncomplete (fs.js:77:15)

Linter - v1.4.3
Linter-rubocop - v0.3.2
Rubocop - v0.33.0

**Comment by matt-thomson** [comment]
I'm seeing similar with a slightly different location:

Error
    at /Users/matt/.atom/packages/linter-rubocop/index.coffee:76:33
    at FSReqWrap.oncomplete (fs.js:77:15)

Same versions

**Comment by dannytip** [comment]
This may be related to RVM.  If i run it on the OSX system ruby (2.0.0) this error goes away.

**Comment by lotap** [comment]
I have the same exact versions and error as @dannytip.
Atom -v1.0.7

I'm specifying the path in the config.cson with:
<code>executablePath: "/Users/username/.rvm/gems/ruby-2.2.1/bin/rubocop"</code>
if I omit rubocop at the end and just use:
<code>executablePath: "/Users/username/.rvm/gems/ruby-2.2.1/bin/"</code>
then I get [Issue #6 - spawn EACSS](https://github.com/AtomLinter/linter-rubocop/issues/6)

**Comment by thibaudgg** [comment]
Almost the same for me:

```
Error
Error
    at /Users/Thibaud/.atom/packages/linter-rubocop/index.coffee:76:33
    at FSReqWrap.oncomplete (fs.js:77:15)
```

Using chruby with: `executablePath: "/Users/Thibaud/.gem/ruby/2.2.3/bin/rubocop"`

Atom: 1.0.7
Linter - v1.4.3
Linter-rubocop - v0.3.2
Rubocop - v0.33.0

**Comment by wurde** [comment]
Same issue, same versions:

Atom: 1.0.7
Linter: 1.4.3
Linter-rubocop: 0.3.2
Rubocop: 0.33.0

**Comment by jensljungblad** [comment]
Same issue

Atom: 1.0.7
Linter: 1.4.3
Linter Rubocop: 0.3.3
Rubocop: 0.33.0

**Comment by afurm** [comment]
Same issue

**Comment by tgaeta** [comment]
Same issue, same versions:

Atom: 1.0.7
Linter: 1.4.3
Linter-rubocop: 0.3.2
Rubocop: 0.33.0

Seeing this in .rb files.

**Comment by lotap** [comment]
I updated to linter-rubocop 0.3.3. Now I have the same issue as @tgaeta.

**Comment by travis-anderson** [comment]
I also see this issue, but only in specific files. Unsure what exactly is special about these files, however.

**Comment by mrfoto** [comment]
Just got the same issue.
atom 1.0.7
linter 1.4.3
linter-rubocop 0.3.3

**Comment by luisdoubrava** [comment]
Same here
atom: 1.0.7
linter: 1.4.3
lineter-rubocop: 0.3.3
doesn't seem ruby or rvm related, happens with:
2.2.2 with rubocop installed in @global gemset
2.0.0 with rubocop installed in @global gemset

**Comment by Noloche** [comment]
Same here
atom: 1.0.8
linter: 1.4.3
linter-rubocop: 0.3.3

**Comment by dogweather** [comment]
Same error, I'll try with a different Ruby.

**Comment by caseywebdev** [comment]
I'm not sure what's causing this. I've released `0.3.4`, which will show the contents of both STDOUT and STDERR when an error occurs. That should help diagnose the issue here, so please upgrade when you get a chance.

**Comment by mrfoto** [comment]
```

File 0Project 0No Issuesengines/blog/app/controllers/public/news_sitemap_controller.rb1:1
LFUTF-8Rubyb-epic-public-pages-verticalization-new-skill-talents-blocks
Error: STDOUT:{"metadata":{"rubocop_version":"0.31.0","ruby_engine":"ruby","ruby_version":"2.2.3","ruby_patchlevel":"173","ruby_platform":"x86_64-darwin14"},"files":[],"summary":{"offense_count":0,"target_file_count":2,"inspected_file_count":0}}
STDERR:Is a directory @ io_fread - /Users/mrfoto/Development/toptal/toptal/engines/blog/app/controllers/public
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/processed_source.rb:16:in read' /Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/processed_source.rb:16:infrom_file'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:68:in process_file' /Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:53:inblock in inspect_files'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:51:in each' /Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:51:ininspect_files'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:30:in run' /Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/cli.rb:26:inrun'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/bin/rubocop:13:in block in <top (required)>' /Users/mrfoto/.rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:inrealtime'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/bin/rubocop:12:in <top (required)>' /Users/mrfoto/.gem/ruby/2.2.3/bin/rubocop:23:inload'
/Users/mrfoto/.gem/ruby/2.2.3/bin/rubocop:23:in `<main>'
Error: STDOUT:{"metadata":{"rubocop_version":"0.31.0","ruby_engine":"ruby","ruby_version":"2.2.3","ruby_patchlevel":"173","ruby_platform":"x86_64-darwin14"},"files":[],"summary":{"offense_count":0,"target_file_count":2,"inspected_file_count":0}}
STDERR:Is a directory @ io_fread - /Users/mrfoto/Development/toptal/toptal/engines/blog/app/controllers/public
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/processed_source.rb:16:in `read'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/processed_source.rb:16:in `from_file'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:68:in `process_file'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:53:in `block in inspect_files'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:51:in `each'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:51:in `inspect_files'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/runner.rb:30:in `run'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/lib/rubocop/cli.rb:26:in `run'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/bin/rubocop:13:in `block in <top (required)>'
/Users/mrfoto/.rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/mrfoto/.gem/ruby/2.2.3/gems/rubocop-0.31.0/bin/rubocop:12:in `<top (required)>'
/Users/mrfoto/.gem/ruby/2.2.3/bin/rubocop:23:in `load'
/Users/mrfoto/.gem/ruby/2.2.3/bin/rubocop:23:in `<main>'
    at /Users/mrfoto/.atom/packages/linter-rubocop/index.coffee:47:27
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by demeshko** [comment]
Same here
 atom: 1.0.9
 linter: 1.5.0
 linter-rubocop: 0.3.3

Error: STDOUT:{"metadata":{"rubocop_version":"0.33.0","ruby_engine":"ruby","ruby_version":"2.1.6","ruby_patchlevel":"336","ruby_platform":"i386-mingw32"},"files":[],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":0}}
STDERR:An error occurred while Style/FileName cop was inspecting C:/Users/Lenovo/AppData/Local/Temp/eb09ccefde079e996ffda5890aaf562802042ab4e6f0b0e523ee3cdcf29397a9.
To see the complete backtrace run rubocop -d.
different prefix: "C:/" and "D:/Projects/Rails/uber_store/test/models"
D:/Rails/Ruby21/lib/ruby/2.1.0/pathname.rb:503:in `relative_path_from'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/path_util.rb:14:in `relative_path'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/formatter/json_formatter.rb:49:in `hash_for_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/formatter/json_formatter.rb:28:in `file_finished'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/formatter/formatter_set.rb:54:in `block in file_finished'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/formatter/formatter_set.rb:54:in `each'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/formatter/formatter_set.rb:54:in `file_finished'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:80:in `process_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:53:in `block in inspect_files'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `each'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:51:in `inspect_files'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/runner.rb:30:in `run'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/cli.rb:26:in `run'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/bin/rubocop:13:in `block in <top (required)>'
D:/Rails/Ruby21/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/bin/rubocop:12:in `<top (required)>'
D:/Rails/Ruby21/bin/rubocop:23:in `load'
D:/Rails/Ruby21/bin/rubocop:23:in `<main>'
  at C:\Users\Lenovo\.atom\packages\linter-rubocop\index.coffee:47:27
  at FSReqWrap.oncomplete (fs.js:77:15)

**Comment by mrfoto** [comment]
@caseywebdev any ideas? I gather it's from using chruby and not having gems installed in the system path but in .gem. But it used to work :confused: 
I really like this linter and not having it is making my life worse :smile:

**Comment by steelbrain** [comment]
@mrfoto If I had to guess from @demeshko's trace, it could be because the files that we save in temp folder before each lint, it's horrible to do so and because the stdin support has been added to rubocop (I think so, not sure) we can just drop the temp part and lint the actual file providing it's contents and file path. That could possibly fix this issue

**Comment by mrfoto** [comment]
Yup, [with `-s` flag](https://github.com/bbatsov/rubocop/blob/62d92fd2faddcfcb5733d04627fea830b68ed693/spec/rubocop/options_spec.rb#L93). I provided my trace too above

**Comment by steelbrain** [comment]
@mrfoto give me a few minutes

**Comment by steelbrain** [comment]
@mrfoto Can you try https://github.com/AtomLinter/linter-rubocop/pull/72 and post the console output?

**Comment by caseywebdev** [comment]
It hasn't been release yet...I told you I've been waiting for the rubocop maintainer to cut the new release.

**Comment by caseywebdev** [comment]
This should be fixed by `0.4.0`

**Comment by demeshko** [comment]
atom: 1.0.15
linter: 1.5.1
linter-rubocop: 0.4.0
ruby 2.1.7
[code]
Error: warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.7.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
invalid option: --cache
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/options.rb:17:in `parse'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/lib/rubocop/cli.rb:21:in `run'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/bin/rubocop:13:in `block in <top (required)>'
D:/Rails/Ruby21/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.33.0/bin/rubocop:12:in `<top (required)>'
D:/Rails/Ruby21/bin/rubocop:23:in `load'
D:/Rails/Ruby21/bin/rubocop:23:in `<main>'
  at exit (C:\Users\Lenovo\.atom\packages\linter-rubocop\node_modules\atom-linter\lib\helpers.coffee:32:24)
  at triggerExitCallback (C:\Users\Lenovo\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Lenovo\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[/code]

**Comment by caseywebdev** [comment]
Looks like you have an out-of-date rubcop. Please upgrade rubocop to >= 0.34.0.

**Comment by demeshko** [comment]
update rubocop to 0.34.2

Error: warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.7.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
different prefix: "D:/" and "C:/Users/Lenovo/AppData/Local/atom/app-1.0.18"
D:/Rails/Ruby21/lib/ruby/2.1.0/pathname.rb:503:in `relative_path_from'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/path_util.rb:14:in `relative_path'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/config.rb:162:in `path_relative_to_config'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:235:in `block in file_name_matches_any?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:230:in `each'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:230:in `any?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:230:in `file_name_matches_any?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:198:in `relevant_file?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:202:in `excluded_file?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:64:in `block in remove_irrelevant_cops'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:64:in `reject!'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:64:in `remove_irrelevant_cops'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:49:in `investigate'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/team.rb:33:in `inspect_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:170:in `inspect_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:141:in `block in do_inspection_loop'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:135:in `loop'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:135:in `do_inspection_loop'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:87:in `process_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:57:in `block in inspect_files'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:55:in `each'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:55:in `inspect_files'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:33:in `run'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cli.rb:26:in `run'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/bin/rubocop:13:in `block in <top (required)>'
D:/Rails/Ruby21/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/bin/rubocop:12:in `<top (required)>'
D:/Rails/Ruby21/bin/rubocop:23:in `load'
D:/Rails/Ruby21/bin/rubocop:23:in `<main>'
  at exit (C:\Users\Lenovo\.atom\packages\linter-rubocop\node_modules\atom-linter\lib\helpers.coffee:32:24)
  at triggerExitCallback (C:\Users\Lenovo\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Lenovo\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by caseywebdev** [comment]
That sounds like it's more of a rubocop issue than a linter issue. What happens if you use rubocop directly from the command line?

**Comment by demeshko** [comment]
it works fine in Xubuntu 15.04 (both Atom and Sublime Text 3)and in Windows with Sublime Text 3

**Comment by caseywebdev** [comment]
But you still get that warning, yes?

**Comment by caseywebdev** [comment]
I think what's happening is that warning goes to stderr and so the linter treats it as an error.

**Comment by demeshko** [comment]
I get this warning only in Windows with Atom

**Comment by tgaeta** [comment]
Update: This now works both on Atom and from the CL. I just disabled them and waited for the hotfix. Not sure if it was rubocop or linter. But not having issues as I reported on AUG 25.

**Comment by demeshko** [comment]
i don't have any issue with rubocop linter with Sublime Text plugin

**Comment by caseywebdev** [comment]
I'll update the linter to ignore stderr unless stdout is not present/parseable.

**Comment by caseywebdev** [comment]
@demeshko I just released `0.4.1`, please try that version.

**Comment by demeshko** [comment]
update to 0.4.1
```
Error: warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.7.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
different prefix: "D:/" and "C:/Users/Lenovo/AppData/Local/atom/app-1.0.18"
D:/Rails/Ruby21/lib/ruby/2.1.0/pathname.rb:503:in `relative_path_from'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/path_util.rb:14:in `relative_path'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/config.rb:162:in `path_relative_to_config'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:235:in `block in file_name_matches_any?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:230:in `each'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:230:in `any?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:230:in `file_name_matches_any?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:198:in `relevant_file?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/cop.rb:202:in `excluded_file?'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:64:in `block in remove_irrelevant_cops'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:64:in `reject!'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:64:in `remove_irrelevant_cops'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/commissioner.rb:49:in `investigate'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cop/team.rb:33:in `inspect_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:170:in `inspect_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:141:in `block in do_inspection_loop'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:135:in `loop'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:135:in `do_inspection_loop'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:87:in `process_file'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:57:in `block in inspect_files'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:55:in `each'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:55:in `inspect_files'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/runner.rb:33:in `run'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/lib/rubocop/cli.rb:26:in `run'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/bin/rubocop:13:in `block in <top (required)>'
D:/Rails/Ruby21/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
D:/Rails/Ruby21/lib/ruby/gems/2.1.0/gems/rubocop-0.34.2/bin/rubocop:12:in `<top (required)>'
D:/Rails/Ruby21/bin/rubocop:23:in `load'
D:/Rails/Ruby21/bin/rubocop:23:in `<main>'
  at exit (C:\Users\Lenovo\.atom\packages\linter-rubocop\node_modules\atom-linter\lib\helpers.coffee:32:24)
  at triggerExitCallback (C:\Users\Lenovo\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Lenovo\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by caseywebdev** [comment]
Strange, [you can see here](https://github.com/AtomLinter/linter-rubocop/blob/8a6ab0bfe09cf261d904503d54dda89f88966d5e/index.coffee#L16-L18) that this can only be the case if the rubocop process is returning no/invalid stdout. You might want to create a new issue for this since it's not related to this one anymore.

**Comment by demeshko** [comment]
today i'm update rubocop plugin up to 0.4.4 - now it is fixed!
