### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by Kvothe11011** [AtomLinter/linter-rubocop#67]
Error
  at C:\Users\gerardo\.atom\packages\linter-rubocop\index.coffee:48:27
  at FSReqWrap.oncomplete (fs.js:77:15)

**Comment by Bertg** [comment]
simile issue on OS X here

**Comment by joshsmoore** [comment]
I am getting it to on Mac using latest rubocop 0.33.0

**Comment by bfraser** [comment]
I get this on Linux with Atom v1.0.7, linter-rubocop v0.3.3 and rubocop v0.30.1

**Comment by ntaylor89** [comment]
Same Here. Rubocop 0.33.0, OSX Mavericks.

**Comment by caseywebdev** [comment]
Please let me know if this is still an issue with the `0.4.0` release. Note you'll need to have rubocop >= 0.34.0 installed.
