### ISSUE TITLE
Rubocop not working

### ISSUE THREAD

**Issue by mico** [AtomLinter/linter-rubocop#68]
Installed linter-rubocop but nothing happens, no errors at starting (in console).
No any sign linter is working.
I've tried to add logging to beginning index.coffee and i get output, so plugin loading, but if u put something after:

    lint = (editor, command, args) ->

it's not working.
how can i continue debugging to find cause?

**Comment by steelbrain** [comment]
Have you installed the base linter package?
```
apm install linter
```

**Comment by mico** [comment]
no. after that it starts working. is it possible to install it as dependency automatically?

**Comment by steelbrain** [comment]
Well. The readme clearly states that this package is just a provider for the base linter.
