### ISSUE TITLE
Not picking up .rubocop.yml

### ISSUE THREAD

**Issue by kimroen** [AtomLinter/linter-rubocop#74]
I'm having some problems getting the linter to respect the settings I have in my `.rubocop.yml` in the root of the project directory. For instance, I have specified

```yml
AllCops:
  RunRailsCops: true
```

but none of these cops are being displayed. They show up if I run rubocop from the command line on the file.

As an example, with the following `app/models/car.rb`:

```ruby
class Car < ActiveRecord::Base
  validates_presence_of :doors
end
```

With the above config, I get these two offenses running `rubocop` from the command line:

```
Inspecting 1 file
C

Offenses:

app/models/car.rb:1:1: C: Missing top-level class documentation comment.
class Car < ActiveRecord::Base
^^^^^
app/models/car.rb:2:3: C: Prefer the new style validations validates :column, presence: value over validates_presence_of.
  validates_presence_of :doors
  ^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
```

But in Atom, only the first one is highlighted. Where I'm running the rubocop command from does not seem to matter.

Trying this out is fairly straight forward:

![screenshot atom](https://cloud.githubusercontent.com/assets/520420/9761632/4fe0cb7c-56fe-11e5-934c-1a05aa46a791.png)

Any tips appreciated!

**Comment by caseywebdev** [comment]
Please let me know if this is still an issue with the `0.4.0` release. Note you'll need to have rubocop >= 0.34.0 installed.

**Comment by kimroen** [comment]
After updating `linter-rubocop` to 0.4.0 and restarting Atom, it does seem to work. Yay! :tada:
