### ISSUE TITLE
Latest gem + atom package fails

### ISSUE THREAD

**Issue by joshgarnett** [AtomLinter/linter-rubocop#76]
After updating this morning, I first got an error stating that the --cache parameter wasn't supported.  I went ahead and updated my rubocop gem to fix the error.  The new error I'm hitting is included below:

```
Error: -s/--stdin requires exactly one path.
/Users/jgarnett/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/lib/rubocop/options.rb:25:in `parse'
/Users/jgarnett/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/lib/rubocop/cli.rb:21:in `run'
/Users/jgarnett/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/bin/rubocop:13:in `block in <top (required)>'
/Users/jgarnett/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/jgarnett/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/bin/rubocop:12:in `<top (required)>'
/Users/jgarnett/.rbenv/versions/2.2.2/bin/rubocop:23:in `load'
/Users/jgarnett/.rbenv/versions/2.2.2/bin/rubocop:23:in `<main>'
    at /Users/jgarnett/.atom/packages/linter-rubocop/index.coffee:30:15
    at process._tickCallback (node.js:365:9)
```

**Comment by flynfish** [comment]
:+1: same here

**Comment by flynfish** [comment]
@joshgarnett Found the issue, after the update the command option has `undefined` in it. Remove it and everything is back to normal!

![screen shot 2015-09-28 at 1 12 12 pm](https://cloud.githubusercontent.com/assets/253936/10145818/a724cf58-65e2-11e5-904f-0b2de0d1b267.png)

**Comment by joshgarnett** [comment]
@flynfish good find, that did the trick also.  I wonder how that got set in the first place.

**Comment by caseywebdev** [comment]
That was my bad, it shouldn't happen again in `0.4.4`. Sorry
