### ISSUE TITLE
Error: invalid option: --cache

### ISSUE THREAD

**Issue by shekibobo** [AtomLinter/linter-rubocop#77]
Started seeing this a lot today whenever the linter gets run on ruby files:

```
Error: invalid option: --cache
~/.gem/ruby/2.0.0/gems/rubocop-0.31.0/lib/rubocop/options.rb:68:in `parse'
~/.gem/ruby/2.0.0/gems/rubocop-0.31.0/lib/rubocop/cli.rb:21:in `run'
~/.gem/ruby/2.0.0/gems/rubocop-0.31.0/bin/rubocop:13:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
~/.gem/ruby/2.0.0/gems/rubocop-0.31.0/bin/rubocop:12:in `<top (required)>'
~/.gem/ruby/2.2.3/bin/rubocop:23:in `load'
~/.gem/ruby/2.2.3/bin/rubocop:23:in `<main>'
  at ~/.atom/packages/linter-rubocop/index.coffee:30:15
  at process._tickCallback (node.js:365:9)
```

Atom version 1.0.19
Version 0.4.4
Rubocop executable: `~/.gem/ruby/2.2.3/bin/rubocop --rails`

**Comment by yarafan** [comment]
Try to update rubocop gem. It worked for me.

**Comment by shekibobo** [comment]
After rebooting my computer and getting rid of the --rails option, things started working for me again.

**Comment by hd-deman** [comment]
confirm that it's working after update gem

**Comment by midwire** [comment]
It may be helpful to others, like myself, to see a minimum required version for the `rubocop` gem on the installation section of the readme.

**Comment by Arcanemagus** [comment]
Looks like that was [added](https://github.com/bbatsov/rubocop/commit/498580c8deb690e9b8e0b6e0802416645a527559) in rubocop v0.34.0. A PR updating the readme would be nice, or I'll eventually get to it at some point if not taken care of already :wink:.

**Comment by WillSewell** [comment]
What version of `rubocop-linter` must I downgrade to in order for it to work with `rubocop` at a version less than v0.34.0? I can't upgrade `rubocop` because then it would be incompatible with the `.rubocop.yml` file in my current project.

**Comment by midwire** [comment]
I was unaware that the `.yml` file specs changed during history of `rubocop`. I am currently on 0.37.2 but have been using it for years and never changed the `.rubocop.yml` file in my home directory. If an upgrade does break it, it still may be worth upgrading your `.yml` file, IMO as there seem to be some performance benefits and better default standards.

**Comment by WillSewell** [comment]
The spec has changed, and unfortunately I can't just do an upgrade like that willy-nilly because there are multiple people working on the project.

**Comment by Arcanemagus** [comment]
@midwire: @caseywebdev Is actually the maintainer of this plugin, I just help where I can :wink:

@WillSewell It looks like the `--cache` option usage was [added](https://github.com/AtomLinter/linter-rubocop/commit/1c4282e0b79644f941d024b787689225ddb73f27) in v0.4.0, so if you run `apm install linter-rubocop@0.3.4` you should be on a version that doesn't require that.

**Comment by WillSewell** [comment]
That worked! Thanks. Shame it's not backwards compatible...

**Comment by Arcanemagus** [comment]
@WillSewell You could always submit a PR that detects the version and enables/disables usage of that option :wink:.
