### ISSUE TITLE
Can't find Rubocop under OSX/RVM

### ISSUE THREAD

**Issue by selfagency** [AtomLinter/linter-rubocop#79]
here's my path in both fish (the shell i use):

```
/Users/selfagency/.rvm/gems/ruby-2.0.0-p481/bin /Users/selfagency/.rvm/gems/ruby-2.0.0-p481@global/bin /Users/selfagency/.rvm/rubies/ruby-2.0.0-p481/bin /Users/selfagency/.rvm/bin /Applications/MAMP/bin/php/php5.6.10/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /usr/local/MacGPG2/bin /usr/local/bin /usr/local/sbin /opt/local/bin /opt/local/sbin /Users/selfagency/.rvm/gems/ruby-2.0.0-p481/bin/rubocop
```

and bash (the shell i don't use):

```
/Users/selfagency/.rvm/gems/ruby-2.0.0-p481/bin:/Users/selfagency/.rvm/gems/ruby-2.0.0-p481@global/bin:/Users/selfagency/.rvm/rubies/ruby-2.0.0-p481/bin:/Users/selfagency/.rvm/bin:/Applications/MAMP/bin/php/php5.6.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/selfagency/.rvm/gems/ruby-2.0.0-p481/bin/rubocop:/Users/selfagency/usr/local/bin:/Users/selfagency/usr/bin:/Users/selfagency/.rvm/bin
```

if i type `which rubocop` in either shell, my output is  `/Users/selfagency/.rvm/gems/ruby-2.0.0-p481/bin/rubocop`, which you'll notice is present in both paths.

i also have @aki77's [atom-env-from-shell](https://github.com/aki77/atom-env-from-shell) installed, which doesn't seem to be helping. even if i launch `atom .` from the terminal, whether within fish or bash, i get the following error when looking at an .rb or .haml file:

```
Failed to spawn command rubocop. Make sure rubocop is installed and on your PATH
Close All
Error: spawn rubocop ENOENT
Error: spawn rubocop ENOENT
    at exports._errnoException (util.js:814:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:438:9)
    at process._tickCallback (node.js:352:17)
```

what am i doing wrong?

**Comment by steelbrain** [comment]
How about you do `which rubocop` then paste that path into this package's settings?

**Comment by selfagency** [comment]
Didn't make a lick of difference, unfortunately.

**Comment by steelbrain** [comment]
No, it did, now the error is in the rubocop area. I have been told that rvm or maybe nvm has too dirs, if you replace the `bin` folder at the end with `wrappers`, you end up with an executable that works everywhere.

**Comment by selfagency** [comment]
I just checked and there's no rubocop folder in `/Users/selfagency/.rvm/gems/ruby-2.0.0-p481/wrappers`. :sad:

**Comment by selfagency** [comment]
So after some Googling, I ran `rvm alias create rubocop ruby-2.0.0-p481` but it didn't add anything to the wrappers folder as it's supposed to. :disappointed:

**Comment by selfagency** [comment]
Turns out something was effed up with my local config and I just had to reinstall RVM from scratch. It's all good now.

**Comment by abrahamks** [comment]
I have a similar problem:

> Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'rubocop' (>= 0) among 12 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /Users/abrahamks/.rvm/gems/ruby-2.2.1@global/bin/rubocop:22:in `<main>'
	from /Users/abrahamks/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/abrahamks/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
    at /Users/abrahamks/.atom/packages/linter-rubocop/index.coffee:30:15

Here is my path (From oh-my-zsh shell) `which rubocop`
`/Users/abrahamks/.rvm/gems/ruby-2.2.1@global/bin/rubocop`

If I run rubocop directly in terminal, it works properly without any problem.

I guess there is something related with rvm configuration?

Thanks

**Comment by Arcanemagus** [comment]
@abrahamks If you are using `rvm` you need to create a wrapper script as it relies on shell macros which don't work when you aren't executing the program from a shell.
