### ISSUE TITLE
Silent option is dropped

### ISSUE THREAD

**Issue by velichkoStoev** [AtomLinter/linter-rubocop#80]
```
Error: -s/--silent options is dropped. `emacs` and `files` formatters no longer display summary.
invalid option: --cache
/var/lib/gems/1.9.1/gems/rubocop-0.28.0/lib/rubocop/options.rb:68:in `parse'
/var/lib/gems/1.9.1/gems/rubocop-0.28.0/lib/rubocop/cli.rb:19:in `run'
/var/lib/gems/1.9.1/gems/rubocop-0.28.0/bin/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/rubocop-0.28.0/bin/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
    at /home/velichko/.atom/packages/linter-rubocop/index.coffee:30:15
```

My RVM version is rvm 1.26.11 (master).

**Comment by liquid1982** [comment]
Same thing here with the latest `linter-rubocop`.

* `rbenv 0.4.0`
* `ruby 2.2.3p173`

**Comment by hyb175** [comment]
Same here after updating to the latest **linter-rubocup**.

* rbenv 0.4.0
* ruby 2.1.6

**Comment by caseywebdev** [comment]
Make sure you're using the latest rubocop.

**Comment by velichkoStoev** [comment]
I've updated to rubocop (0.34.2). Still get the same error.

**Comment by liquid1982** [comment]
I just updated `rubocop` and the problem is gone.

@velichkoStoev make sure you installed the gem in your current version, then rbenv rehash as usual

**Comment by velichkoStoev** [comment]
On my local machine I use 

* rvm 1.26.11 (master)
* ruby 2.2.1

**Comment by MaicolBen** [comment]
I have the same issue, and using the last version of rvm and rubocop except ruby (2.2.0), I changed the path settings but it seems that not taking the path, because when it reports an error it shows another route of rubocop. What could be wrong?
