### ISSUE TITLE
Error: env: ruby_noexec_wrapper: No such file or directory

### ISSUE THREAD

**Issue by Deekor** [AtomLinter/linter-rubocop#83]
Atom version: `1.0.19`
Rubocop version: `0.34.2`

Error:
`Error: env: ruby_noexec_wrapper: No such file or directory at /Users/Dee/.atom/packages/linter-rubocop/index.coffee:30:15`

I installed rubocop with `gem install rubocop`

When I run `which rubocop` I get: `/Users/Dee/.rvm/gems/ruby-2.0.0-p247/bin/rubocop` and I have pasted that into the command path under settings.

Any idea how to fix this?

**Comment by steelbrain** [comment]
Try `/Users/Dee/.rvm/gems/ruby-2.0.0-p247/wrappers/rubocop` as the path

**Comment by Deekor** [comment]
Hmm that seems to have made things worse 
<img width="459" alt="screen shot 2015-10-05 at 9 46 38 pm" src="https://cloud.githubusercontent.com/assets/1904267/10299697/a4586bc2-6baa-11e5-808e-e9b50058d997.png">

**Comment by steelbrain** [comment]
Replace `wrappers` with `wrapper` and verify you have that path on disk and try again.

**Comment by hzmangel** [comment]
Thanks @steelbrain , it solves my problem.

@Deekor , the RVM version of rubocop needs some extra environment settings, and the shell script under `wrappers` directory is used for this. Here is the content of my `wrappers/rubocop`

```shell
#!/usr/bin/env bash

if
  [[ -s "/Users/huzim/.rvm/gems/ruby-2.2.1/environment" ]]
then
  source "/Users/huzim/.rvm/gems/ruby-2.2.1/environment"
  exec rubocop "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/huzim/.rvm/gems/ruby-2.2.1/environment'" >&2
  exit 1
fi
```

You can create a similar one with your path, and save it to your linter-rubocop configuration.

**Comment by vzamanillo** [comment]
Closed for cleanup. Be free to reopen it if the problem persist.
