### ISSUE TITLE
Error: dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by edwardloveall** [AtomLinter/linter-rubocop#84]
I recently installed rubocop and got this error:

```
Error: dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/edwardloveall/.gem/ruby/2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace
dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/edwardloveall/.gem/ruby/2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace
  at /Users/edwardloveall/Code/dotfiles/atom/packages/linter-rubocop/index.coffee:30:15
```

Since I run multiple ruby versions, I put rubocop in `/usr/local/bin/rubocop`. Anything I can try to fix this?

**Comment by davidrichards** [comment]
I found that JSON version 1.8.2 was created to fix this issue, but it's crept back in to version 1.8.3.  Here is the related discussion online: [https://github.com/flori/json/issues/229](https://github.com/flori/json/issues/229)

To fix this, I just added a JSON dependency to version 1.8.2 in my Gemfile until this stabilizes.

**Comment by waitingallday** [comment]
I had the same problem trying to run rubocop and scss linters on sublime - changing back to 1.8.2 had the same errors, but 1.8.1 worked fine for me. This is on a fresh El Capitan install, ruby 2.2.3.

**Comment by edwardloveall** [comment]
One thing that I'm experimenting with is Atom's environment. On OS X if you launch an app (any app) from the command line it will have the environment variables of that shell, but if you launch it from the finder/dock it won't.

You can see this if you open the Atom console `opt`-`cmd`-`i` and type `process.env`. It's significantly different when launched via the command line or the dock.

If this is in fact the problem, you can add that path to the init script of atom:

```coffeescript
process.env['PATH'] += ':/usr/local/bin'
```

That directory comes from where rubocop is located with a `:` in front (which is how paths are separated). You can get your directory with:

```shell
$ dirname `which rubocop`

/usr/local/bin
```

Try this and tell me if it helps.

**Comment by sdahlbac** [comment]
@edwardloveall thank you for that suggestion, I had the same problem. the above seems to have helped.

**Comment by edwardloveall** [comment]
I also found that running `/usr/local/bin/rubocop` outside of atom in the terminal gave me this same error. Switching back to a newer version of ruby and rubocop fixed it. ¯\_(ツ)_/¯

**Comment by edwardloveall** [comment]
Another fix, specify the version of json in your Gemfile:
```ruby
gem 'json', '1.8.2'
```

then run:

```shell
bundle update json
```

**Comment by edwardloveall** [comment]
Another thing to try, (since I keep running into this, searching for the error message, and finding this issue) is to `gem uninstall rubocop` and `gem install rubocop` ¯\_(ツ)_/¯

**Comment by aeberlin** [comment]
These steps fixed the issue for me:

1. `process.env.PATH` in `init.coffee`
2. `gem pristine ...` for `rubocop` and `json` versions

Now 1.8.3 works fine for me.

**Comment by edwardloveall** [comment]
Back again with more hot tips & potential fixes:

I found a rogue json gem in my system gems:

```shell
$ sudo gem list

json (2.0.3, 1.8.3)
```

`sudo gem uninstall json` removed that `2.0.3` version which I was seeing in my error logs and got rubocop working again.

**Comment by Arcanemagus** [comment]
Closing this as it's a user environment issue and nothing to do with how this package operates, thanks everyone for the great troubleshooting tips!

**Comment by kylewelsby** [comment]
For those searching for a solution, this fixed it for me. 

```
gem pristine json
bundle pristine json
```
