### ISSUE TITLE
Getting this error every time I open a ruby file

### ISSUE THREAD

**Issue by ProLoser** [AtomLinter/linter-rubocop#85]
Error: warning: parser/current is loading parser/ruby21, which recognizes warning: 2.1.7-compliant syntax, but you are running 2.1.2. warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri. invalid option: --cache /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/options.rb:68:in parse' /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/lib/rubocop/cli.rb:19:inrun' /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/bin/rubocop:13:in block in <top (required)>' /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/benchmark.rb:294:inrealtime' /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubocop-0.30.1/bin/rubocop:12:in <top (required)>' /usr/local/var/rbenv/versions/2.1.2/bin/rubocop:23:inload' /usr/local/var/rbenv/versions/2.1.2/bin/rubocop:23:in `

'

**Comment by caseywebdev** [comment]
Upgrade to the latest rubocop and it should work.

**Comment by ProLoser** [comment]
Thanks!
