### ISSUE TITLE
[Enhancement] Switch/reload rubocop config on the fly.

### ISSUE THREAD

**Issue by jonathanhills** [AtomLinter/linter-rubocop#87]
A command palette option and/or keyboard shortcut to switch between different `.rubocop.yml` files or reload the current one would be awesome. At the moment I have to disable/enable the package to reload, and change the settings by hand to switch.

**Comment by tirdadc** [comment]
I noticed this issue when switching from one [project](https://github.com/danielbrodin/atom-project-manager) to another. It would be nice if it reloaded the current project's .yml.

**Comment by Arcanemagus** [comment]
Marking this as closed, I'm not sure how this package was operating when this was filed but as it currently just launches `rubocop` and lets it determine the configuration any issues with that would be from `rubocop` itself.

Please comment further or file a new issue if this is still a problem!
