### ISSUE TITLE
Not working when using rvm

### ISSUE THREAD

**Issue by elpdspec** [AtomLinter/linter-rubocop#92]
Hi,
In the terminal, Rubocop is working fine. 
In atom, it is not. no error message. I already set the path to Rubocop.
Any guidelines ore assistance will be appreciated.

**Comment by Arcanemagus** [comment]
Are you using `rvm`? If so you will need to use the wrapper version as the normal shell function version won't work within Atom.

**Comment by elpdspec** [comment]
Thank you for the reply.  I do use rvm but not familiar with the wrapper function. If you know how to create one to use with atom it will be great.

**Comment by Arcanemagus** [comment]
I'm not familiar with it myself, but it looks like the steps should be similar to [this comment](https://github.com/AtomLinter/linter-rubocop/issues/4#issuecomment-46378274).

**Comment by elpdspec** [comment]
Ok, I have made a wrapper that works in the terminal. If anyone interested the script is below. 

In Atom I still get nothing. 

I opened to dev tools and tried to debug the index.coffee. In the js lint on js file I can catch a break point stop. In rubocop linter on rb file, I can't. It does not seems to call the main linter function. It does not reach the first line with the `convertOldConfig()` call.  I am not an expert of coffee script or Atom plugins. Just thought to check. Any Ideas ?


```bash
!/usr/bin/env bash

if
  [[ -s "/home/user/.rvm/gems/ruby-2.2.4/environment" ]]
then
  source "/home/user/.rvm/gems/ruby-2.2.4/environment"
  exec rubocop "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/user/.rvm/gems/ruby-2.2.4/environment'" >&2
  exit 1
fi
```

**Comment by Arcanemagus** [comment]
Try closing Atom and deleting the `~/.atom/compileCache` folder.

**Comment by elpdspec** [comment]
Thanks for the suggestion. Tried it and it did not work. Updated Atom version from 1.24 to 1.3 and tried that again. No success. Open to other suggestions.  Is there a way to debug the point where the plugins are loaded in atom ?

**Comment by alexanderadam** [comment]
@elpdspec you should rename the ticket as this haven't to do anything with kubuntu.
It works for me under (k)ubuntu 15.10, but I'm using rbenv instead rvm.

**Comment by Arcanemagus** [comment]
@elpdspec Sorry, looks like this got dropped in my notifications at some point.

When you run `Editor: Log Cursor Scope` in a file you think it should be working on what scopes do you see listed?

**Comment by elpdspec** [comment]
Thank you for the reply. I don't remember now how it was fixed, but I did install from scratch a new version of atom and played with the settings again from what I do remember.

**Comment by Arcanemagus** [comment]
So you are no longer seeing this issue?

**Comment by elpdspec** [comment]
Yes. I can't mark this issue as closed.
